### ISSUE TITLE
Intl.Segmenter is not implemented in Firefox

### ISSUE THREAD

**Issue by chibicode** [vercel/satori#14]
`Intl.Segmenter` was introduced here https://github.com/vercel/satori/pull/12 but it's not yet implemented in Firefox ([compatibility table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter#browser_compatibility)), causing an error for `/test`:

<img width="787" alt="Screen Shot 2022-02-06 at 10 02 59 PM" src="https://user-images.githubusercontent.com/992008/152733189-4bc60c5b-bf0f-436c-adbc-fd79d5a16a2d.png">

**Comment by Samirox66** [comment]
Is there a way to use satori in Firefox?

**Comment by shuding** [comment]
@Samirox66 You can setup https://github.com/surferseo/intl-segmenter-polyfill before using Satori.
