### ISSUE TITLE
README example incomplete

### ISSUE THREAD

**Issue by rozenmd** [vercel/satori#166]
# Bug report

## Description / Observed Behavior

`robotoArrayBuffer` is undefined in the example located here: https://github.com/vercel/satori#overview

## Expected Behavior

I expected the example to be runnable

**Comment by alexincore** [comment]
I found that robotoArrayBuffer should be a binary (Uint8Array) representation of TTF/OTF/WOFF file, which you can get by adding some kind of arraybuffer loader to your bundler, i.e. https://www.npmjs.com/package/@wemap/rollup-plugin-arraybuffer for Rollup.
Hope that helps those trying to run the example..

**Comment by ducaale** [comment]
Using a loader might not be necessary. Here is what worked for me:

#### Read font from disk
```js
const fontArrayBuf = await fetch(fontUrl).then(res => res.arrayBuffer())
```

#### Get font from network
```js
import fs from 'fs/promises'
const fontArrayBuf = await fs.readFile(fontPath)
```
