### ISSUE TITLE
HTML example looks broken in Playground: Tailwind CSS.

### ISSUE THREAD

**Issue by hmu332233** [vercel/satori#167]
# Bug report

## Description / Observed Behavior

The HTML example looks broken in Playground: Tailwind CSS.

![image](https://user-images.githubusercontent.com/10302969/195056375-774581ab-13ca-4545-8306-16c96bc66e5b.png)

## Expected Behavior

I expected the example to look right.

## Reproduction

[Share Link](https://og-playground.vercel.app/?share=xVRNb9swDP0rgoahl6h2m7brjLQ7dMMwYLtsO_oiR7StVh-GJNcxgvz3UfLcOkUx7NZDYpKPJt8jZe3p1gqgBc0y8sMKWUsQpOIe_60hbQidL7IscKkGaUQvT7dWZ_jrrAETfKa5e4AgTZN52AZpjc-2gbPZKU1pNkI-loYQH0YFN_t9tAlpQTZtKMjJWZ6_P1lNwUGK0L6ICek7xUeM1gp2czTan6Wb2iC2tarXZka5ko35FkD7CCFRcDN03_sg6_HOYtDE_sdwxbcPjbO9EXdWWYf40MoAE3w4lOY2GlESCcNNSauGNY6P7DJPlEqa8GVGDCeMIUeiRZFsZwcysLpXinQjOzsn3Y5dRBSbac8mUjNZVkEYAAzp2PVTB-zRnr_WIsAusPVOEa-LZF-gXaNeVlklSHAoERfGQlzAlJ0kfMzzyVNQh0UbbOQ7bm5_AhcjCRY38ghEmk-bLMVf5E2UUiE8MbKx7CrPsdyvwF0go-0dqR0A8pAcyVrBx9MXlTZZe_7sPE1SB3adZMY5oROrLpofTzztEATTgviWCzscJWM6J62DGtPflXTx3qvz_-sualbWCYxMD4YzNajAYRrBE_GsO671Mm54PY02flnTLjQI2espmo4Y8vsKAb8SHBOITcaX2jIU96pWrbD0mwtOAv5P69GZ-A7cGaKtg3_pXXrP9mzNT7qitkuXDi32NN0ktLj6sF7R6aqhxfr6akUFVH1Di5orDysK2t7L32MXb0D8xKKHdSLpL7oCQYvgejgc_gA)

## Additional Context

Maybe it's because iframe doesn't have tailwind css.

**Comment by shuding** [comment]
This is kinda expected because HTML doesn't have built-in Tailwind supported, but maybe we can do something in the playground...
