### ISSUE TITLE
Wasm compile error

### ISSUE THREAD

**Issue by korac** [vercel/satori#172]
Copied from [the docs example](https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation#getting-started), I get the following error when calling an API function:

```
error - [Error [CompileError]: WebAssembly.compile(): Compiling function vercel/og-image#64 failed: invalid value type 'Simd128', enable with --experimental-wasm-simd @+3457
```

Env:
- @vercel/og: `0.0.15`
- next: `12.2.3`
- node: `14.18.2`

The feature looks promising and I wonder do I miss something?

**Comment by shuding** [comment]
Satori [requires Node.js >= 16](https://github.com/vercel/satori#runtime-and-wasm) as it uses both WASM SIMD and `Intl.segmenter`.
