### ISSUE TITLE
`0` should be considered as valid angle

### ISSUE THREAD

**Issue by shuding** [vercel/satori#184]
# Bug report

## Description / Observed Behavior

`linear-gradient(0, red, rgb(0, 223, 216))` does not work which is valid CSS. Thanks to @yisibl for reporting!

Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/angle#setting_a_null_angle

## Reproduction

https://og-playground.vercel.app/?share=XVJNb8IwDP0rUaaJTeogg1K2inHYh7QddtokLr0EYkJYmlRpyqf473PaFTEuif2e7Wc7OdC5FUBTOhZqnRlCSr_T8HQ4BJuQJSi59Cnp3DN23YkacKOEX15gQpWF5jtEFxq2LRrsV-Vg7pU1yM2trnLTslwraT485GWgwHhwLbWqSq8WuxeLoAn6_-kZn_9IZysjPnIuAXmtDHB3Jx0XCkNvWEQcCDzkLNj9_gCP--T29tQalv5Se8wd9M-g6d_ACWM1ejxmZhKMcbmWZ-M_ZXQ0zGiDrBVsnu0WMUYYGQ1JcqIWSmvErxhjLdRumOTcSRXWEnKKbacWI6SWQ8GC-yURmPw5GHWHj93-UA-S7iNWj9-7Sdw4d0m8z-hk3AvRTaM97LSx8Ekv1b5tkZKYodTkHbS2EZlap8W4h7GY1N40orYIj1bS9EDriWn6gDuhzY-gaRwcAbNK0nTBdQkRhdyu1PeuCN_Jb2oP64StvuUzEDT1roLj8Rc

**Comment by hacknug** [comment]
Similar thing happens with `opacity`. When using `0` as a value the styles are dropped while using something like `0.000001` produces the expected result.

**Comment by jueungrace** [comment]
@hacknug is the `opacity:0` issue still happening for you? And if so, could you share some repro code?

**Comment by hacknug** [comment]
> @hacknug is the `opacity:0` issue still happening for you? And if so, could you share some repro code?

That one seems to be resolved in the latest version (v0.0.43). Thanks for the ping!
