### ISSUE TITLE
Unknown file extension .wasm 

### ISSUE THREAD

**Issue by shrirambalaji** [vercel/satori#194]
# Bug report

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/11358903/195596796-52f40f64-15ab-4322-9c9d-3305736132f6.png">

## Description / Observed Behavior

What kind of issues did you encounter with Satori?

This isn't directly an issue with satori, but when following the @vercel/og docs to try to move away from puppeteer, I've found this issue.

## Expected Behavior

Ideally, this should compile as I assume the webpack / swc configuration to compile wasm files properly. 

## Reproduction

The source is at https://github.com/shrirambalaji/og-shrirambalaji/tree/feat/use-vercel-og

## Additional Context

I've also tried removing, .next folder and uninstalling and reinstalling node_modules multiple times.

- node version: v16.18.0
- @vercel/og: "^0.0.18"
- next: latest
- react: 18.1
- pnpm: 7.3.0

Not sure if I'm missing something here, maybe a next config change cc @shuding

**Comment by shuding** [comment]
Hey @shrirambalaji, I think you missed this config in the API route:

```jsx
export const config = {
  runtime: 'experimental-edge',
}
```

Without that it will be a Node.js function, which isn't supported by `@vercel/og` at the moment — we plan to support it soon though!

**Comment by thvozdovic** [comment]
Hey, I'm actually experiencing the same issue, perhaps it is related to pnpm?

I do have the config exported in my route

**Comment by shuding** [comment]
@thvozdovic can you share your Next.js version?

**Comment by shuding** [comment]
@TinsFox Please try with Next.js >= 12.3.0, as listed here: https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation#requirements

**Comment by TinsFox** [comment]
> @TinsFox Please try with Next.js >= 12.3.0, as listed here: [vercel.com/docs/concepts/functions/edge-functions/og-image-generation#requirements](https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation#requirements)

It turns out that it would be better to highlight it here, because it is not particularly conspicuous now. Or can we check dependencies when satori is installed
