### ISSUE TITLE
Add more information about asm.js/WASM/native differences

### ISSUE THREAD

**Issue by shuding** [vercel/satori#201]
It would be great to have these (maybe reorganized a bit) added to the README:

> When running in the browser, the main difference is that WASM files need to be hosted and fetched, before initializing. Where asm.js can be bundled together with the lib. And then of course WASM should be faster.
>
> When running on the Node.js server, native should be faster. However there are Node.js environments where native modules are not supported (e.g. StackBlitz's WebContainers), or other JS runtimes that support WASM (e.g. Vercel's Edge Runtime, CloudFlare's worker, or Deno).
>
> Of course there are other difference between asm.js, native and WASM, such as security and compatibility.
>
> Overall there are many trade-offs between each choice, and it's better to pick the one that works the best for your use case.

_Originally posted by @shuding in https://github.com/vercel/satori/discussions/192#discussioncomment-3869126_

Thanks @wong2 for calling it out!

**Comment by ShaswatPrabhat** [comment]
Hi, I can take a shot at this if still open.
Thanks in advance.
