### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'create') while useing in browser

### ISSUE THREAD

**Issue by ideaspace** [vercel/satori#209]
# Bug report

I am trying to use this library directly in browser but I am getting error

## Description / Observed Behavior

```
satori.ts:43 Uncaught TypeError: Cannot read properties of undefined (reading 'create')
    at vu (satori.ts:43:26)
    at main.js?t=1665833998825:12:19
```

## Expected Behavior

run well and give the SVG

## Reproduction

```
import satori, { init } from 'satori/wasm'
import initYoga from 'yoga-wasm-web'

const yoga = initYoga(await fetch('/yoga.wasm').then(res => res.arrayBuffer()))
init(yoga)

const data = await (
  await fetch('/inter-latin-ext-400-normal.woff')
).arrayBuffer()

const svg = await satori(
  {
    type: 'div',
    props: {
      children: 'hello, world',
      style: { color: 'black' },
    },
  },
  {
    width: 600,
    height: 400,
    fonts: [
      {
        name: 'Inter',
        data,
        weight: 400,
        style: 'normal',
      },
    ],
  }
)
console.log(svg)
```

## Additional Context

"satori": "^0.0.41",

Running in vite vanilla template, with Node 16

**Comment by wong2** [comment]
Where did you get the `yoga.wasm`?

**Comment by ideaspace** [comment]
> Where did you get the `yoga.wasm` file?

The public directory in vite vanilla template, it works ok

**Comment by shuding** [comment]
That error (`Cannot read properties of undefined (reading 'create')`) looks like Yoga is wrongly provided or not provided.

**Comment by ideaspace** [comment]
I am sure the Yoga was provided
The code runs in browser runtime mode that follows the document of `Runtime and WASM` section

**Comment by wong2** [comment]
> > Where did you get the `yoga.wasm` file?
> 
> The `public` directory in vite vanilla template, it works ok

Can I have a link to the `yoga.wasm` file?

**Comment by ideaspace** [comment]
> > > Where did you get the `yoga.wasm` file?
> > 
> > 
> > The `public` directory in vite vanilla template, it works ok
> 
> Can I have a link to the `yoga.wasm` file? I suspect something is wrong with it.

I just copied the `yoga.wasm` file to the `public` directory from the `yoga-wasm-web` package
