### ISSUE TITLE
Does "fetch" really need to be polyfilled?

### ISSUE THREAD

**Issue by eggsy** [vercel/satori#230]
# Bug report

## Description / Observed Behavior

I love Satori, it is really easy and somehow powerful to use with. One drawback I encountered was that it (I think) tries to reduce the amount of external dependencies by using the built in `fetch` since it's mainly meant to be used on JSX components and not real Express.js like API services... This is an issue though. I have a Nuxt.js 2 app which I need to create meta images for my blog posts, I got it working by defining an ReactNode object but that's really hard to deal with and gets really complicated over time. Also, images don't work since my Nuxt app doesn't really work well with newer Node versions. Isn't there a way to use another dependency, maybe `whatwg-fetch`, `axios` (even), or some other simple HTTP library to overcome this issue once and for all? It would really make everything easier.

![image](https://user-images.githubusercontent.com/13917975/196272747-9fd1ca35-feb9-46e0-9fa7-2df94251bbfe.png)

## Reproduction

Here's my [website's source code script](https://github.com/eggsy/website/blob/main/scripts/generateOgImage.ts) for creating meta images (it's called after Nuxt is done generating my static website).

**Comment by shuding** [comment]
> And even when I do import "whatwg-fetch" to polyfill the fetch API to my project, it says XMLHttpRequest is not defined

I think you will need to use https://www.npmjs.com/package/isomorphic-unfetch (browser + Node.js), `whatwg-fetch` seems to be a browser polyfill from that error.

Regarding Satori, I guess the best we can do here is to have an option to provide a "data fetching API", to fetch external resources (`(url: string) => Promise<Response | http.ServerResponse>`). When missing, it will try to use the global `fetch`.

**Comment by eggsy** [comment]
Here are the amazing previews for some of my blog posts: 

<table>
	<tbody>
<tr>
		<td>
			<img src="https://eggsy.xyz/og-images/erasmus-icin-pasaport-almak.png" width="400" />
		</td>
		<td>
			<img src="https://eggsy.xyz/og-images/okul-gunlukleri.png" width="400" />
		</td>
</tr>
<tr>
		<td>
			<img src="https://eggsy.xyz/og-images/slowly-yeni-koye-eski-adet.png" width="400" />
		</td>
		<td>
			<img src="https://eggsy.xyz/og-images/premid-nasil-kullanilir.png" width="400" />
		</td>
</tr>
	</tbody>
</table>

And if anyone's wondering the source, it's the same as [reproduction link](https://github.com/eggsy/website/blob/main/scripts/generateOgImage.ts). Love satori 💜.

**Comment by shuding** [comment]
Agreed @wong2. Maybe we should throw and tell people to polyfill it if `fetch` isn't available.

**Comment by jsonnull** [comment]
What about scenarios where the image doesn't actually need to be resolved?

If the image has width and height attributes for layout, could a "pass-through" mode be supported where the image source is preserved in the svg without needing to resolve it over the network?

**Comment by shuding** [comment]
> If the image has width and height attributes for layout, could a "pass-through" mode be supported where the image source is preserved in the svg without needing to resolve it over the network?

You can pass a data URI to `src` in that case

**Comment by wong2** [comment]
Shall we close this issue?
