### ISSUE TITLE
Implement whiteSpace: pre-line

### ISSUE THREAD

**Issue by MillHaus33** [vercel/satori#231]
I am rendering dynamic text, and I need to be able to render new lines without pre-wrapping spaces

**Comment by rxxndy** [comment]
Here is an example of how text is rendering for us: 

<img width="932" alt="Screen Shot 2022-10-18 at 12 18 27 AM" src="https://user-images.githubusercontent.com/48290359/196350769-a11a2908-e70e-4581-8f00-775efca1d4fe.png">

**Comment by hbeckeri** [comment]
its happening
