### ISSUE TITLE
Background image property fails to load image

### ISSUE THREAD

**Issue by neilff** [vercel/satori#234]
# Bug report

## Description / Observed Behavior

Over on the Vercel OG Image Playground, when trying to use the CSS property `backgroundImage`, I am encountering an error:

```
Can't load image 'https://www.stedi.com/images/opengraph/stedi-opengraph-template.png': Unsupported image type: unknown
```

![image](https://user-images.githubusercontent.com/3271978/196494891-9ca1dcf0-d089-4a5c-95b2-4f395e944694.png)

If I flip over to the HTML tab, the content loads as expected:

![image](https://user-images.githubusercontent.com/3271978/196495103-b086a553-2219-40c4-84bf-3b12ef59bd15.png)

I also noticed that when using the same image in an `img` tag, it loads the image as expected:

![image](https://user-images.githubusercontent.com/3271978/196495436-fa40bf8b-d640-4b05-8f66-a45e814e678a.png)

---

When I try to use this same property locally in my Next.js code, I encounter an error as well, but the message is different:

```
Error: Can't load image 'https://www.stedi.com/images/opengraph/stedi-opengraph-template.png': Only absolute URLs are supported
```

## Expected Behavior

`backgroundImage` property should be able to load an image

## Reproduction

- Navigate to https://og-playground.vercel.app
- Paste the following code:

```
<div
  style={{
    height: '100%',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    fontSize: 32,
    fontWeight: 600,
    backgroundImage: "url('https://www.stedi.com/images/opengraph/stedi-opengraph-template.png')",
  }}
>
  <div style={{ marginTop: 40 }}>Hello, World</div>
</div>
```

## Additional Context

Our application is currently using version `0.0.26` without any issues. We have noticed this error when upgrading to the latest version of `0.0.42`.

**Comment by wong2** [comment]
Change `backgroundImage: "url('https://www.stedi.com/images/opengraph/stedi-opengraph-template.png')"` to `backgroundImage: "url(https://www.stedi.com/images/opengraph/stedi-opengraph-template.png)"` works

**Comment by Sam-Apostel** [comment]
I have a fix ready this issue. I'll write some tests and make a PR later today.
