### ISSUE TITLE
Output PNG images only generated partially on prod

### ISSUE THREAD

**Issue by transitive-bullshit** [vercel/satori#237]
# Bug report

## Description / Observed Behavior

Sometimes, my Vercel edge function OG images only render part of the target PNG instead of the whole PNG, though the output image is still the correct size.

Take the following edge endpoint: https://transitivebullsh.it/api/social-image?id=d1b5dcf8-b9ff-425b-8aef-5ce6f0730202 (source https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/main/pages/api/social-image.tsx#L46)

Here are some example images generated by this endpoint:

(they are all 1200x630, but the first two are clearly cut off and rendered incorrectly)

![social-image-1](https://user-images.githubusercontent.com/552829/196511824-e513622a-022a-49a2-b266-68dfdedd90a9.png)
![social-image-2](https://user-images.githubusercontent.com/552829/196511842-d6446710-e547-4b6e-bd09-9036a1a10c92.png)

Note that this is a normal Next.js application running on Vercel.

## Expected Behavior

The following (correct) image is generated sometimes, but sometimes upon a cache miss, the incomplete version is generated instead:

![social-image-correct](https://user-images.githubusercontent.com/552829/196511906-64b8ffc2-1187-44ba-8fbe-a90e46eabf43.png)

## Reproduction

Visit https://transitivebullsh.it/api/social-image?id=d1b5dcf8-b9ff-425b-8aef-5ce6f0730202 and refresh until you get a cache miss, and it will sometimes repro. I have no idea why this happens sometimes and sometimes it renders the full, correct PNG image.

## Additional Context

This may belong in `@vercel/og`, but that doesn't appear to be open source. I haven't been able to reproduce this issue locally or with the playground.

**Comment by david-buck** [comment]
I'm also having this issue, but not sporadically. 

I have one for rending stop cards fro public transport
https://catchy.nz/api/ogimage/stop?stopName=test&stopType=bus
https://catchy.nz/api/ogimage/stop?stopName=test&stopType=train
https://catchy.nz/api/ogimage/stop?stopName=test&stopType=ferry
https://catchy.nz/api/ogimage/stop?stopName=test&stopType=cableCar

and another for rendering trip names

https://catchy.nz/api/ogimage/trip?tripName=After%20Midnight%20(Lower%20Hutt%20-%20Petone%20-%20Wellington)&routeId=N8&schoolBusSchool=&routeColor=%23000000&tripType=bus&routeType=3

In all cases, the first 88 rows of pixels are rendered and then transparent pixels after that. 

There are no errors showing in my Vercel function logs

**Comment by codingholt** [comment]
Having the same issue here. -->[https://www.svennijholt.nl/api/image?title=test](https://www.svennijholt.nl/api/image?title=test)
Yesterday it was working, I just redeployed, and now it isn't working anymore in prod, but locally it is still working. 
Also, no errors in my Vercel function logs.

[image api endpoint code](https://github.com/codingholt/portfolio-site/blob/main/pages/api/image.tsx)

**Comment by kalwabed** [comment]
Facing the same issue. It isn't working anymore in prod.

**Comment by rwlc** [comment]
Same here. Works in my dev environment, but fails to load the entire image in production

**Comment by yannglt** [comment]
Same here 🙃 Works perfectly locally but fails to load the image in production, no errors showing in logs

**Comment by transitive-bullshit** [comment]
Update: the generated images are now consistently mostly blank.

1200x630 example image generated from https://transitivebullsh.it/api/social-image?id=d1b5dcf8-b9ff-425b-8aef-5ce6f0730202

![social-image (1)](https://user-images.githubusercontent.com/552829/197346003-871c959c-ed41-47d2-ace0-487b0f01a6ff.png)

**Comment by david-buck** [comment]
This seems to be fixed 
https://twitter.com/vercel_status/status/1583956970650112001?t=JBLQJCDlTemDhC9vPUHMBg&s=19

**Comment by kalwabed** [comment]
Yes, just fixed. Thanks @david-buck

**Comment by shuding** [comment]
Closing this for now as the issue should be resolved. 👍

**Comment by transitive-bullshit** [comment]
It seems to be more stable now, but if I run a batch GET on all the OG images of my site, about 4% of them still return partial 4KB PNG images. The partial images seems to be inconsistent (retrying after cache timeout works manually for me), but they look similar to the ones I previously linked above.

I did manage to catch a console error for one of them:

> Error: Cannot perform I/O on behalf of a different request. I/O objects (such as streams, request/response bodies, and others) created in the context of one request handler cannot be accessed from a different request's handler. This is a limitation of Cloudflare Workers which allows us to improve overall performance.

**Comment by jinwookie** [comment]
I know this issue is closed, but we are still experiencing this issue today pretty frequently on our Vercel edge function, where our images are partially cutting off, so it looks like the service has degraded?

<img width="362" alt="Screen Shot 2022-11-10 at 3 07 58 PM" src="https://user-images.githubusercontent.com/15899863/201195622-befdfd91-1b9f-40fb-aff0-a968d232d9ff.png">

<img width="362" alt="Screen Shot 2022-11-10 at 3 07 43 PM" src="https://user-images.githubusercontent.com/15899863/201195740-59a068c3-7f7b-4bdb-bf8f-d1e0b0333eeb.png">

**Comment by smaeda-ks** [comment]
UPDATE

For those who had experienced a similar issue even after our initial status update, we actually found another problem on our Vercel side that could cause this malformed image generation under certain conditions. It's been fixed and this should not be happening more. We're sorry for the trouble! And appreciate your reports.

**Comment by transitive-bullshit** [comment]
Thanks @smaeda-ks 🙏 

If anyone else wants to batch-test their social images, and you have a sitemap, you can run:

```bash
npx warm-social-images https://transitivebullsh.it/sitemap.xml
```
