### ISSUE TITLE
Access to the underlying Yoga layout tree

### ISSUE THREAD

**Issue by tarngerine** [vercel/satori#239]
# Feature Request

## Description

I'm looking for a way to get the computed Yoga layout tree. Debug option paints it into the SVG — but i'd love a way to get this myself.

## Additional Context

The use case is I want to implement some custom text truncation logic, where I need the be able to call some equivalent of `getClientBoundingRect`, but in yoga land that stuff is already calculated — just hidden inside the satori library :)

**Comment by shuding** [comment]
I'm not sure about this feature request, one reason is that Yoga is the underlying implementation detail and the structure might change any time. And also, we've been considering moving to another layout engine in the future, maybe https://github.com/DioxusLabs/taffy. 

Another way to support this is to add some kind of callback hooks, that will be triggered for each node in different layout phases. But that would be something hard to implement and maintain.

**Comment by theetherGit** [comment]
I'm looking for this engine implementation because sometimes i get this

```bash
sveltekit-og/node_modules/.pnpm/yoga-layout-prebuilt@1.10.0/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

[LinkError: WebAssembly.instantiate(): Import #0 module="wbg" function="__wbg_new_651776e932b7e9c7" error: function import requires a callable]
```

**Comment by shuding** [comment]
Done in #457!
