### ISSUE TITLE
Punctuation effecting line breaking.

### ISSUE THREAD

**Issue by david-buck** [vercel/satori#252]
I think there are some side effects of using `Intl.Segmenter` to break strings apart., and then using rules to re-stick strings back together:

segment widths don't seem to get recalculated when more than one re-appended character is added:

In this example here, if the frame is 1px narrower, the second string wraps
![image](https://user-images.githubusercontent.com/5119820/197333201-ab3193f9-0c94-45ce-b4d1-4ebd650789b9.png)
![image](https://user-images.githubusercontent.com/5119820/197333220-c58d54be-6915-4aff-b319-0da01e44d889.png)

Adding other punctuation breaks the layout and forces the string to continue outside frame:
![image](https://user-images.githubusercontent.com/5119820/197333253-5affa409-8db6-4385-8cfd-2360ddda4e28.png)

The case that is effecting my usage is words with a left parenthesis `(` before them get broken and not reattached:

![image](https://user-images.githubusercontent.com/5119820/197333654-89bd94ba-f95d-422f-ab38-a0208c1f0b42.png)

**Comment by david-buck** [comment]
Sorry, I should have been clearer - the first example is good and expected!

**Comment by LuciNyan** [comment]
Hi! @david-buck! Just wanted to let you know that we've rewritten the logic in that section and it looks like your issue has been resolved. Thanks for your detailed report!
