### ISSUE TITLE
Support multiline text overflow ellipsis 

### ISSUE THREAD

**Issue by blueset** [vercel/satori#253]
# Feature Request

## Description

> What do you want to add to Satori, and why?

It would be great to have multiline text overflow ellipsis support in Satori. Sometimes when generating OG thumbnails, there are cases where the text overflows the size of the canvas. We surely do not want the text to overflow, but we also don’t want to limit the text to one line just to have the ellipsis indicator, as it is always better to make efficient use of the space available on the canvas. 

## Additional Context

> You can add a shareable link using https://og-playground.vercel.app, or any other context that helps explaining this feature request here.

There is an existing WebKit-only implementation of this feature: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp

**Comment by LuciNyan** [comment]
That's cool. I'd be happy to work on this! <3
