### ISSUE TITLE
Error: Satori is not initialized

### ISSUE THREAD

**Issue by tbuddhika** [vercel/satori#257]
# Bug report

## Description / Observed Behavior

In local setup, Satori is returning the following error when generating the SVG,
`Uncaught (in promise) Error: Satori is not initialized: expect `yoga` to be loaded, got undefined`

Source code: https://codesandbox.io/s/bf6282

## Expected Behavior

Satori should return the SVG string.

## Reproduction

- Download the above source code.
- Install dependencies (yarn install)
- Run the application (yarn run start)
- Click on **download** button
- Check the console logs.

## Additional Context

Satori version: 0.0.43
OS: macOS
Node: v16.18.0

**Comment by tbuddhika** [comment]
Yes, it works on sandbox but the same example isn't run on the local environment. (Additional Context)
I have gone through the documentation everything looks the same.

**Comment by wong2** [comment]
Following the reproduction steps, I get another error:

> Uncaught ReferenceError: process is not defined

**Comment by tbuddhika** [comment]
@wong2, Yes, me too. Any clue?

**Comment by shuding** [comment]
I believe this has been fixed in newer versions.
