### ISSUE TITLE
Aspect ratio of an image

### ISSUE THREAD

**Issue by XxPKBxX** [vercel/satori#264]
# Bug report

## Description / Observed Behavior

Aspect ratio of an image can't be set.

## Expected Behavior

Tried to resize an `<img />` object with CSS, or `width` and `height` props. It should be resized freely.

## Reproduction

![image](https://user-images.githubusercontent.com/29917385/198052629-3a8fcb83-bb0c-4804-95e5-cce299706042.png)

## Additional Context

Satori version `0.0.43`

**Comment by shuding** [comment]
Should be fixed in #285.
