### ISSUE TITLE
Unsupported image format .jpeg in img tag

### ISSUE THREAD

**Issue by jmduke** [vercel/satori#265]
# Bug report

## Description / Observed Behavior

The image does not work for some JPEGs, namely `https://dl.airtable.com/.attachments/bdb4a3a340204a938b004d2d9c999f2f/649b8723/White_Noise.jpg`

## Expected Behavior

Image tag should be able to render valid image formats

## Reproduction

https://satori-playground.vercel.app/?share=XZFNT4QwEIb_CqkxXja0C2SFZtfL6sGLF032QmL6BXQtLaHFFQn_3XZxjXrq9HmnnZl3JsAMFwCDLZfvpY4i60YldtMU4ihqhKwbh6ObNULXN6sFniR3zT_Gpe0UGT2tlPi40BDfy14wJ432GjNqaPVFJUrW-tGJ1gZJaCf6i3QcrJPVuDce6lD_r0wJe6t7M2i-N8r0Xr-qquqnqn_1LD8FjtLkFzp8z7JB6EznudR3IdjKtl7SbM92JWic6yyGkKuYyN4RqkTMTAtj4hxhTetbsZBympGUpBlKUEaKNKcIZTzhBSuKokoquMkKmt8mKTw00onXJyOtiI9dXYJSQ193C73j_gQrYLrgjwV4AmdvAc7z9Qos5gOc-YYBF3SoAXb9IFZAtOYoX8YuLM6dzjf_TRjyoaWCL2nz_AU

## Additional Context

This is on 0.0.43. I noticed a similar issue (https://github.com/vercel/satori/issues/202) but that seems unrelated and not a regression.

**Comment by wei** [comment]
Seems to be working now. 
<img width="1773" alt="image" src="https://user-images.githubusercontent.com/5880908/201923713-9a411d1a-6e78-4c4c-85d3-e9e06f0ad9f5.png">
