### ISSUE TITLE
gradient color is passes over black

### ISSUE THREAD

**Issue by Sam-Apostel** [vercel/satori#267]
# Bug report

## Description / Observed Behaviour
Gradients pass through black while mixing.

<img width="176" alt="Screenshot 2022-10-26 at 23 50 47" src="https://user-images.githubusercontent.com/16917762/198145297-82e6a297-94a4-422c-92ca-89e38c391636.png">

## Expected Behavior
<img width="176" alt="Screenshot 2022-10-26 at 23 50 54" src="https://user-images.githubusercontent.com/16917762/198145285-a19396fb-06e5-41ce-ba7b-1619b06c4e34.png">

## Reproduction
https://og-playground.vercel.app/?share=bY8xbsMwDEWvInBqARU1ig6FkGYpOmTPqEWOGFmJTBoyHccwfPdYyZhs_B-PxOMMB_YIBjY-Xiwp1cuU8Heey6zUGL00Rln4qqruakE_6gZjaOS5r93hHDIP5P84cS7A2ETBF8CudQELkCKhyx8hOx-R5G3ClHjUSrKjvnN57d4tlPVlsbS1tPlcVbeggTuJTD2YGe6eYH6qSsNDDsx3CR7rIYA5utSjBmz5FPdTVx6W8Z7WO0cm-W9r9GAkD7gsNw

## Additional Context

note that this does not occur in radial gradients with only 2 color without positions. 
> eg: `radial-gradient(circle at 0px 0px, yellow, transparent)`

**Comment by shuding** [comment]
I think unfortunately this is due to the SVG behavior, not sure what's the best way to resolve it — guess `transparent` should be resolved to the nearest color's RGB with A=0? What about `yellow, transparent, red`?

**Comment by tobua** [comment]
I would say it should use the nearest background color, possibly adding the (transparent) gradients below. If there is no backgroundColor use the default white.

**Comment by tobua** [comment]
Well, even though this looks bad, it seems like this is just how gradients are rendered in SVG. Same black is added in between when rendering in the browser. Obviously, `resvg-js` is just copying that behaviour. The look differs from gradients when rendered as regular CSS which is what most developers expect the gradient to look like. Since this tool transforms the markup into an SVG and then renders this as PNG I don't think there is anything that can be done here.

**Comment by Jackie1210** [comment]
just dig into this problem. As shown in the spec，svg treat `transparent` in `stop` equals to `stop-color` black and `stop-opacity` 0. @shuding

**Comment by viztor** [comment]
https://tailwindcss.com/docs/gradient-color-stops 

> Gradients fade out to transparent by default, without requiring you to add to-transparent explicitly. Tailwind intelligently calculates the right “transparent” value to use based on the starting color to avoid [a bug in Safari < 15.4](https://bugs.webkit.org/show_bug.cgi?id=150940) that causes fading to simply the transparent keyword to fade through gray, which just looks awful.

Seems Tailwind fixed something somewhat similar to this

**Comment by shuding** [comment]
Yep I noticed that too: https://twitter.com/shuding_/status/1479518587723386887. Wonder how Chrome implements this, my guess is that if you have a gradient of the following, it does these steps:

- yellow with 50% alpha, transparent, red
- (1, 1, 0, 0.5), (?, ?, ?, ?), (1, 0, 0, 1)
- (1, 1, 0, 0.5), (1, 0.5, 0, ?), (1, 0, 0, 1) // calculates the RGB for `transparent`
- (1, 1, 0, 0.5), (1, 0.5, 0, 0), (1, 0, 0, 1) // set A to 0 for `transparent`
