### ISSUE TITLE
No context accepted

### ISSUE THREAD

**Issue by Lschulzes** [vercel/satori#274]
Hi there, thanks for providing such tool.

I have a doubt, I with to generate a somewhat complex image, that uses  chakra-ui providers to colors and React context under the hood. The ImageResponse is not able to return the component, is it a expected behavior? Can I use webpack to compile and then insert it in the @vercel/og?

```
return new ImageResponse(
    (
      <ChakraProvider theme={theme}>
        <BracketsForImage initialData={INITIAL_DATA}>
      </ChakraProvider>
    ),
    {
      width: 1200,
      height: 600,
    },
  );
  ```

**Comment by shuding** [comment]
This is by design. The "JSX" used by image generation is pure and stateless, and it's not React (React isn't even a required dependency). They are equivalent to the JSON representation of JSX elements. Related: https://github.com/vercel/satori#documentation
