### ISSUE TITLE
Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by sahithyandev** [vercel/satori#275]
# Bug report

## Description / Observed Behavior

It gave the following error which seems impossible for a starter to debug.

```
D:\Projects\satori-test\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at D:\Projects\satori-test\node_modules\satori\dist\index.cjs:8:20073
    at Array.map (<anonymous>)
    at yt.getEngine (D:\Projects\satori-test\node_modules\satori\dist\index.cjs:8:20064)
    at nn (D:\Projects\satori-test\node_modules\satori\dist\index.cjs:5:13532)
    at nn.next (<anonymous>)
    at bt (D:\Projects\satori-test\node_modules\satori\dist\index.cjs:8:16716)
    at bt.next (<anonymous>)
    at eo (D:\Projects\satori-test\node_modules\satori\dist\index.cjs:9:28898)
    at D:\Projects\satori-test\index.js:13:23

Node.js v18.9.0
```

## Expected Behavior

Work as intended, lol. Otherwise, provide enough info on what have I done wrong.

## Reproduction

Reproduction: https://github.com/sahithyandev/satori-test

I did not use https://og-playground.vercel.app to create the reproduction as I am trying to run Satori locally. 

## Additional Context

Satori version: 0.0.43
Node.js version: 18.9.0

**Comment by hrichiksite** [comment]
I'm facing the same problem every time I try to generate an image (SVG) with the lib.

**Comment by sahithyandev** [comment]
@hrichiksite You can fix the issue following my comment (or see https://github.com/sahithyandev/satori/commit/ed71509a4646ee8bd880c710ed020492c72f50ee)

I hope your PR will be approved.

**Comment by Rohithgilla12** [comment]
Thanks for this wonderful library.

Any update on this issue @shuding ? 😄

**Comment by jeetiss** [comment]
@Rohithgilla12 could you approve that bug can be reproduced with latest version of `satori`?

It seems like your version depends on `yoga-layout-prebuilt` but satori has used `yoga-warm-web` for a while

**Comment by Rohithgilla12** [comment]
Yes, I have tested it with the latest version of satori and I'm still able to reproduce it

**Comment by felixhaeberle** [comment]
@shuding Thanks for building this great library!! 👍 :)
I'm also facing this problem, has somebody already found a solution expect of patching the code?

**Comment by shuding** [comment]
I'll prioritize it and make sure to have it fixed soon.
