### ISSUE TITLE
<img> always renders a square and doesn't respect different width/heights.

### ISSUE THREAD

**Issue by robertgonzales** [vercel/satori#277]
# Bug report

## Description / Observed Behavior

I'm trying to render images that are not 1:1 aspect ratio but Satori is always rendering `<img>` tags as a square.

## Expected Behavior

Respect different width/heights. If I set `width={200}` and `height={50}` the image block should be 200px wide and 50px tall.

## Reproduction

[OG Playground Link](https://og-playground.vercel.app/?share=XZDBTsQgEIZfhUxi9lK31WhiSOvF6BN45EILpexShgB1tyF9d2m7etgTM1-A_5tJ0KGQQKEW-odZQkKcjWxSWmtCBqnVECk5PFXVw6HY4UWLONwxoYMzfM60N_K602Vh9n0taj0qst8LvmsYDDG6QMuSO3d0-mpGbI8djqVBhY-C-_PRWcXg9mbLa9JzVS03sms16fWf_GkTbE-yi186S7M8m41cWwYFaXl3Vh4nKz7QoKcMvBQ5YpUkpMyedZlXkE8oAF3UaAPQBFs40LeqKmCPBfqyNkK2kwLacxNkAXLEk_6e3brKeNm6_E-f8z_HVgqg0U9yWX4B)

**Comment by monkyver** [comment]
Same problem here, image is not rendered, just a white square (color can be changed if I add the proper style as in the example)

**Comment by shuding** [comment]
Fixed in #285 (it was a terrible typo...), will cut a new release for `satori` and `@vercel/og` today.
