### ISSUE TITLE
Linear gradient not working for "to top right" and similar directions

### ISSUE THREAD

**Issue by joulev** [vercel/satori#278]
# Bug report

## Description / Observed Behavior

While `linear-gradient` works very well with `to top`, `to right`, etc., it crashes for `to top right`, `to bottom right`, etc.

Locally, the error is

```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
```

On the playground the error is clearer:

```
undefined is not an object (evaluating '{0:[0,1,0,0],top:[0,1,0,0],bottom:[0,0,0,1],left:[1,0,0,0],right:[0,0,1,0]}[l.orientation.value]')
```

## Expected Behavior

`linear-gradient` should work normally.

## Reproduction

[Playground](https://og-playground.vercel.app/?share=zVbbbtswDP0VQUWRFHM2N7cWRjdgt4c-b8Be_CJbtK1OlgxJXpIF-fdRcVTES1ekBZo1QGyKIo_OoSzTa5prDjShN1z8ShUh1q0kvF-vvU0IF7aRbJWQQSFhOYg6711rnShWn7VyoBxO2oblMMrALQBUiGJSlOrWQW136SPrmHFhusDsb-I3JGQ83XP9AFFWiDmP453XwdJ99FgII6G4B2gY50KVCbkKkbmW2mCUAR6CMpb_LI1uFb-tWYmLDaRQwMyoNIwLZD90mjjdEOOXjcjZZDLlsxiNPMsZm10EoGrHa3AZx-fBuRDcVcHnXZtNqj6kypu-oPfVPCgk8bcvwkDuhPbKkHtbqwEiYL7Hfl5-RGpmSqE-aed07anNGh8eSnNWFMXeIoR4R7D7S-7vBgr0SRUsGYdc1EzevMPgQHXffjHa-LuKD7hvvc8RQN4QZ5jCR9eAylen1WPKbDidRaT7X_RU_TV3tDbM-58iIhK_nTympAt4ihz2sJ5gvd5TVlk5vLyeR2Q8PsfL_Lxfl8Pp4x9ge-KThwuyPlncy_hQ0INBT5H1j81-KV2LSjjoiUjp1pfSo1k32GigwH7CO1iiWA32tDry1uD7y22HPTm20q3kJAOCLI-WlNJ9wJQ-fgK7O42objxrS5M13fZEmlxj_6Zd06TJ1A84ZG1Jk4JJCxGFWt-J76vGf3vgZ4MfIY5n9LXOgNPEmRY2mz8)

## Additional Context

Local versions:

* `@vercel/og` v0.0.20
* `satori` v0.0.43

**Comment by shuding** [comment]
Good catch - as a workaround you can use degrees for now.
