### ISSUE TITLE
Images rendering as white squares

### ISSUE THREAD

**Issue by monkyver** [vercel/satori#290]
# Bug report

## Description / Observed Behavior

When trying to add images (both as <img> or as div background style, images are rendered as white (or the background color set in the code):

```
import presenter from  "../../../assets/img/presenter.png";
...


<div
                    style={{
                      display: 'flex',
                      backgroundColor: "#2991c7",
                      opacity: 1,
                      borderRadius: "50%",
                      left: '2%',
                      alignSelf: 'center',
                      width: '5px',
                      height: '5px',
                      backgroundImage: `url(${presenter})`
                    }}
                >
```

<img width="1114" alt="Screenshot 2022-11-07 at 17 10 59" src="https://user-images.githubusercontent.com/65304248/200358997-8b36a49d-5ab1-4393-9f27-fc3ce0d157b3.png">

## Expected Behavior

Images are rendered normally

## Additional Context

Satori 0.0.44

**Comment by shuding** [comment]
Which framework are you using and what's the value of `presenter`? 

```js
import presenter from  "../../../assets/img/presenter.png";
```

When you are using that value as the background image, it needs to be either a base64 data URI string, or a URL of that image that can be fetched.

**Comment by shuding** [comment]
Closing as no more information provided.
