### ISSUE TITLE
Support Non-breaking space

### ISSUE THREAD

**Issue by tvler** [vercel/satori#293]
# Feature Request

## Description

Allow `<span>Word1 Word2&nbsp;Word3</span>` to work as expected: Carries down both Word2 and Word3 to a new line if needed

## Additional Context

Example of non breaking space not working: https://og-playground.vercel.app/?share=nZBPS8QwEMW_ShiRvRQ2_kEk1AVRwbvCXnJpm2kbTTOlTV1rzHc36boie9xc8ub3mGHmeahIIQjIlf6QlrHRzQbvvE-asRZ10zrBVhecn6-yPdxp5dojpvTYm2KOtDb4eaBJP-oBK6fJRq8iM3X24JZF9d4MNFn1QIaG6J_Vdf3XS9a96C8U7OryH9r-bnTD-UJDkHaTRD72hd14Cd8nvGc0hqScOL_nWxqMkhDy9TJR2nwds4k_ZEB9umQE4WFJAcRt3AP2MYG4ToXCcmpA1IUZMQPs6E2_zn3K2O2WKs5Jlzx1JSoQbpgwhB8

Thank you for releasing such an excellent open source library!

**Comment by sahithyandev** [comment]
I gave it a quick look, and hope I am on the right track. I have made a WIP PR.

**Comment by sahithyandev** [comment]
As #362 is closed as a wontfix. Support for `&nbsp;` won't be added.

To use a non breaking space, you would have to use the unicode ` ` or `\u0a00`.
In my PR, the non breaking space character seem to work. But I am not totally sure about its behavior.
