### ISSUE TITLE
Bug: Text doesn't render when immediately followed by an emoji

### ISSUE THREAD

**Issue by tvler** [vercel/satori#302]
# Bug report

## Description / Observed Behavior

```
Hello🦺
```

 is rendered as

```
     🦺
```

## Expected Behavior

`Hello🦺` is rendered as `Hello🦺`

## Reproduction

https://og-playground.vercel.app/?share=bZFLTsMwEECvYg1C3UQifISQVbopSLAGiU03STxOXBw7ih1KiHIWdhyCU3EEPCmhH2XlmffkGc-4g8wKBA5zod5WhjHnW423XUcxYwWqvPCczc7j-HQWbeFGCV8cMaFcpZM2UKnxfaQU36kaM6-sCS6zuinNaBOtcvPosXSk0HisR7VunFeyXdoADfU_1GmSvea1bYxYWm3r4E-klP9dw60n9YGcXV7soZe_Wa7jeKB9vzILCmj0xc_n1_cDam3nZ5QecDYlBsZIT4lpTnRXaDwhAlvRhhzwDobtAr8Jr4Tt-oFfUSIwbXLgMtEOI8DSrtVzW9Hf-c2QhTo0532ZogDu6wb7_hc

## Additional Context

There also seems to be some text layout glitching when an emoji is placed in between characters `Hel🦺lo` (as seen in the example link)

**Comment by en30** [comment]
https://github.com/vercel/satori/blob/58668d57be537e5477515446fd0e92b977071d85/src/text.ts#L494-L556
In this part of the code, the current behavior is likely to be as follows.

- `Hello🦺`.
    - The last `word` (=`'🦺'`) is image, so the `wordBuffer` (=`'Hello'`) is not added to the generated SVG
- `Hel🦺lo`.
    - The `wordBuffer` is added to the SVG as `'Hello'` at the stage of processing `'lo'`.

Adding `&& !graphemeImages[words[i + 1]]` to the `continue` condition, the behavior became expected. I am not sure this change breaks the intent of the changes around kerning in #258...

**Comment by shuding** [comment]
Thanks @en30 that's a good fix!
