### ISSUE TITLE
Bug: Incorrect wordBreak: 'break-word' wrapping

### ISSUE THREAD

**Issue by tvler** [vercel/satori#308]
# Bug report

## Description / Observed Behavior

Observed: 

[playground link](https://og-playground.vercel.app/?share=xZLLTsMwEEV_xRqEuikiFISQBSx4fAGV2HTjxJPE1PFEjkMIUf4dO22qpAi29cbje_0413YHCUkEDvdSfW4MY5VrNT50XagZy1FlueNscRVF54vlTmyUdPmRJlVVatF6NdX4NaqhflEWE6fIeC8hXRdmdGORbDNLtZHPpMl6_yxN08NaMu5NfSNn16uJ9L4nuo2iQe37jXkMRQhwRL8HXfmpbJ5nIv2mqIQu6EDZkJVPFsXWO3HoL4LyX-6-H4AYE_M2UF56TG__QVwImymzpjIgzq_75Cn8sVrTNMTYwxKoDE9cAe9g4AV-5-FgRwr8JgwkxnUGPBW6wiVgQR9q3Zbh87lmGPl9whO_FjFK4M7W2Pc_)

<img width="216" alt="image" src="https://user-images.githubusercontent.com/4934193/201759654-7ce2ff29-ff2f-43a1-8271-29491fb26fdc.png">

"Hello" should wrap down to the 2nd line if `wordBreak: 'break-word'` is set, instead of breaking up the word.

## Expected Behavior

Expected: https://jsbin.com/niyamefoqi/5/edit?html,output

## Additional Context

https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

**Comment by abielzulio** [comment]
Got the same bug here, any solution?
