### ISSUE TITLE
@vercel/og Error: Unsupported Image Type

### ISSUE THREAD

**Issue by odiseo0** [vercel/satori#311]
As it says in the title, the problem is related to @vercel/og and not to this repository as such, but I don't know any other place to ask.

I am using `ImageResponse` to generate the image as it says in the documentation, everything works fine, the problem starts when I try to use an image that is not either jpg/png.  I want to use `webp`.

You can follow the instructions of the official docs for [@vercel/og](https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation)

Code I used:
```js
import { ImageResponse } from '@vercel/og';


export const config = {
  runtime: 'experimental-edge',
};

export default function handler() {
  return new ImageResponse(
    (
      <img
        alt="Vercel"
        height={200}
        src="https://via.placeholder.com/302"
        style={{ margin: '0 30px' }}
        width={232}
      />        
    ),
  );
```

You'll get a blank page and in the terminal you should see:
```console
Error: Can't load image https://via.placeholder.com/302: Unsupported image type: unknown
    at eval (webpack-internal:///(middleware)/./node_modules/satori/dist/index.wasm.js:16:2973)
```

My questions are, what are the supported image types? If there a way to make `ImageResponse` accept `webp`? and have anyone else faced this issue, if you did, what were your solutions? Thanks

**Comment by odiseo0** [comment]
Hi @itbruno, thanks for the response. I was looking to use `webp` instead of `png` or `jpg`.

I didn't know that placeholder.com accepted extensions, thanks for that too.

**Comment by itbruno** [comment]
@odiseo0 Satori haven't `webp` support yet. Can you see this issue about this point: #273

**Comment by odiseo0** [comment]
Thanks for the help, I'll leave the issue open for a while in case someone have some sort of solution

**Comment by digitaltopo** [comment]
I'm seeing the error `Unsupported image type: unknown` for `.png` images. I've both `backgroundImage` and an `<img src>` tag. Any thoughts on why this would be happening?

**Comment by kodiyak** [comment]
You can use this approach to temporarily solve this problem:

```typescript
import axios from 'axios'
import sharp from 'sharp';

const getImageBase64 = async (url: string) => {
  return axios.get<ArrayBuffer>(url, {
    responseType: 'arraybuffer',
  }).then(async (res) => {
    const buffer = await sharp(res.data).toFormat('png').toBuffer()
    return {
      url: `data:${'image/png'};base64,${buffer.toString('base64')}`,
    };
  })
}
```

Then use

```jsx
const image = await getImageBase64('https://via.placeholder.com/302.png')

return new ImageResponse(<img src={image.url} />)
```

**Comment by kenjinp** [comment]
> #273

This workaround isn't possible in edge environments because sharp relies on `child_process`, it's probably not suitable for many `vercel/og` usecases

**Comment by jishnubmc** [comment]
Hi, 
I am facing same issue. Is there a better work around for this that work on edge functions. The fun fact is that I can render images in all format without any issue locally but gives issue when hosted on vercel.

**Comment by wottpal** [comment]
Same problem here, any edge workaround has come up?

**Comment by odiseo0** [comment]
Better late than never
