### ISSUE TITLE
Image not loaded inside SVG

### ISSUE THREAD

**Issue by birdglove2** [vercel/satori#312]
# Bug report

I tried to put the image inside an SVG both in `base64` and `url` format 
In the [playground](https://satori-playground-git-fork-sahithyandev-fix-background-i-7197fe.vercel.sh/?share=7RiJbtpI9FcsV6u2agLjCwLbVuIqOIvJgaM0KFJk7LEZY3u89hgDUf5939gGQjdVu1qtVK0CAr837z7meexH0aYOFtviR4es7iNBSNkmwJ8eHzksCAtMvAVrC28lhH57e1Iu5sRhi2_WHJLGgbWBVTfA690qh_skwTYjNAKaTYMsjHZUKyBepDMcppyEI4aTHcnPUkbcTY_CYsTtH5Pnlr30EppFTo8GNAH6G9d191ZBakq2uC0o8rOl2yqWBkJ88enpPvrMgfvoY7ryyqg-3YvyWeNerALnqNQCdEVw3qVrwJGABGARynWXBAEsRjTCgK3DIEoBXTAWt-v1PM9ruVKjiVeXEUJ1sLJjaq8DEi1fZJVarVa9IN-L4N9HjxuB2IE5S4J3b0oMPTgP0oP8vuSJLbYQHOAwJFUR0Fg-k2paQwUnUa2pjdSaqmgtZVwQZwe3C30gC_oiBKqEdGHF-DTBkYMTEnnAYidQ2IHj4fRerB-b0mpKQ0E8E6gma6XyWktCkiyDA6jWUJoVbVSxctMpS-gSg_w8gCL-nM26x_8d7Kb8WiZAINyJo2Tw5PIKFdFKCqAbjsL1UFutJslnx_U9gxSVOQFVNxFhvIRZipNpbNn4IrpJeW2hdWlySngXxjSweEOfliKcPb0edstSuPhLQKkDrQ__pxRUELZzI8FpFnCj3X3_6qHl4S9kXUXq4qKhDYslZC2QCHinNEts3AnihQUq2CbmyQsLBt6YVpBh7gHvyx99JbkpHPmxsBKn0lyZv3DdFDPB4S6r-9WhlaUpsaJukCVQQaePV6RIAU_gM9fDmKaEYXBcPtYu0BgnFqO8i2nGXoz2X4XG24zHVuntBtBPQgijrdidSWgFoLF066XkH1KCXRfGlfTgJDSeLiyH5mVr_UDxvlDDxIoXxN5b-56-g8ViA-w6vWypaqPxfVn2-W6TglwFVqNx16907oOZLo8KNhGMqmddLz3vd0C4duhvoRgy7UWCXVh_Q3gyUOUcS6wodSE8oBQwdDx-h2qS1EJq672Q2lbAcYQUWT5TIf0ANZoNtQljpIyk8pPDheoykCMr-22pHI_cZrGVn3vnWMxqF7J8in6AGfr73EpxQz25HE3k2aarzm_Xmb1FxBpdI7tPV2PFUZyNphgbbWWH9srwO7nRa22d0Cb6aBbPvjq9ueK1dL_jGb3OdkL4T_9wOeounKHnzcIgnfcR0dFseIUMdN3TvRngpmnIen-g3m073sVU1Sb9AbvoqfnEXHqG6TH4FdeC1uvkY3Ogjk0vM_o3WgkP1Csuy2VIRx37HdAHPnC5oaGN_SUypp2c29D7XO6upJkeGW_Vs9ntOrW-drezaTe0AL6c6v7Ev0MTE2RI18fgo2EOsslU9-6UJcQ32Iz9G4j5XAXeHawBLHH4p3X6V_9Ipz38gqzei_qWl9PzSRGTf-6PTSOb-PoWcsAmRM0N32Zj_2pjEMTzBfCdcjFFmWEa67GpQ63QRu_zawfpffDJXEp6n-d-APXoyCCb87xD_oD_hq9DLXgddGZM1a3hD5hB1LWxBZygDaxnF6a9Bb-Vix4C_w1lsumALOj8Sl-M5Xo5G-7iAN0bQwFt_cL-GnwBO53Cd4N0ENcz6fFYrsAPhDDRV5d-vrKVWXTpfYLeLrfL7u7G-xuur4eS10PJ66Hk9VDyeij5dQ8lfEymMCeZUnOZ7US1CLO6H3t1JNdbWl1u1NVGXWmghy8PckuTG2qjqT3YQf7HbE29zmI9nrbSvtRQTG-5lW6NUfqndH1eAwXfvyeQ0CsfaAWW80kDz9fCnCYwpU7VHVDNsIqv-FhFTSFly9PDo_Mxy74u8HR8RDgU6VtKmtivR7PXo9n_-Gh26Ha-IQ_Yr7gP_8Np9Pc08LeF-1eFQmglHolMGrcFFcGLtc8jHAT0RLilSeDAGCOrcpwVV_FEpDG_Tadi-1EswhXbTal5IpYRiu2GrJ2IDp5nnth2rSDFJyIOqU9MuBfDm0qWFxjo4W_1BuEcO2KbJRl-evoL), it is shown that the `base64` is working fine but not with the `url` (See Figure 1)

Figure 1
![CleanShot 2565-11-17 at 13 38 31](https://user-images.githubusercontent.com/57980797/202374475-d565824f-f769-46a1-b9b5-0641199c56e3.png)

However, both of them don't work on my local (See Figure 2)

Figure 2
![image](https://user-images.githubusercontent.com/57980797/202374517-0fe7686d-e695-485d-b773-bc9c454c6b3f.png)

I have tried put the `base64` and `url` in `<img/>` tag but both do work fine.
So I think the problem is from the SVG in Satori. (See Figure 3)

![CleanShot 2565-11-17 at 13 43 27](https://user-images.githubusercontent.com/57980797/202375357-ca7e94ac-279b-48db-aa27-e17e08631e8b.png)

## Additional Context

vercel/og version ^0.0.20

**Comment by shuding** [comment]
Yeah this is something we haven't implemented, good catch. Basically Satori needs to fetch the image for `<image>` tags in SVG nodes too.

**Comment by yisibl** [comment]
Just for reference: resvg-js implements `<image>` loading in v2.1.0
https://github.com/yisibl/resvg-js/blob/main/CHANGELOG.md#added-1

**Comment by Jackie1210** [comment]
@shuding I am working on this issue with https://github.com/vercel/satori/issues/468
