### ISSUE TITLE
`fontFamily` requires the font name to include quotes

### ISSUE THREAD

**Issue by shuding** [vercel/satori#334]
# Bug report

## Description / Observed Behavior

Reported by https://sdorra.dev/posts/2022-11-27-social-media-cards, the font name is required to contain `""` like `<div style={{ fontFamily: '"Cabin"' }}>Hello from Cabin</div>`

## Expected Behavior

Satori should be able to match the font even if it doesn't have the quotes.

## Reproduction

n/a

## Additional Context

n/a

**Comment by sahithyandev** [comment]
Is this still an issue? It seems to be working.

https://og-playground.vercel.app/?share=fVFNT8MwDP0rkRHapRLlQwhFY5cBggOnIXHpJW2cNiNNqiRllKr_naRrJ0DTTonfs5_97B4KwxEoLLn8zDQhzncK7_s-_gmpUJaVp2Rxmabni2QP7iT31T-MS9co1gVUKPya0fh_kBYLL40OXGFUW-uZZUqW-sVj7SKF2qOdqW3rvBTd2gRQx_5_6ZwVH6U1reZro4wN_JkQ4tA1VG3kN1JyffULep-83KbpiA5DpleZjsYPrsfEJ1ZLFa1k8BpCh9YyTzZtblnHOMtgEWpXz6iUWV6E6tMixySOCEwvJGCauC0HtIdx00DvwsSwPwXQmxhwzNsSqGDKYQJYm61865p4R78bo6ATp3isc-RT3jD8AA

**Comment by shuding** [comment]
Ah interesting, if it's working we need to add a test case

**Comment by sahithyandev** [comment]
I am trying to add a test for this. But the font in the test is never changing. I couldn't find why. Roboto font is being used even if I set `fontFamily: "RobotoMono"`.

https://github.com/sahithyandev/satori/blob/03167e0752e4e1292a09f12e57c17e7d92a662a9/test/font.test.tsx#L38-L81
