### ISSUE TITLE
Broken `pre-wrap`

### ISSUE THREAD

**Issue by shuding** [vercel/satori#335]
# Bug report

## Description / Observed Behavior

`pre-wrap` seems to be broken and can't render the text. `pre-line` works correctly.

## Reproduction

https://og-playground.vercel.app/?share=hVLBbtQwEP2VkRFaCQWxi6oKRaWXwoFzi7jsoY49id11PJbtNIQo_8443RSWC4co9nvPb97YMwtFGkUtbrR9PnqAlCeHn-e5rAEM2s7kGnaH_f7trnoBR6uz-QfTNgUnJ0Zbhz83tKy_2IgqW_LMKXJD7zdWOtv5bxn7VCj0GeNGPQ0p23a6IwZ9qX9JN1KdukiD13fkKDL_pm3b16p86t7-whoO139BP869XO_3K7osR39bFqX1175hNDbjfZCKz-9CxPdjlGHH6tv58YGglyeE76corbfSQ0MxKZMrmGjgi3EOPKKGbJBrOkej9R3wF1FbbiHVR88l38EBQokP1EKD2Faghsy6TJB6yS7BosK0Sq-YC2lTQhMpm7OHk7FDIM-3yw6GQkC9Uh9BOXrG9VQno7Oqgt569Yc-WybDyTQnVrJpZIcXxlyPOwuIjgWS03ZR5rPFplEycqD_qQJlmelCpe2W5lDSlDArBJl61mJ6XG4-8MvwE21_UQkKZZSSqGexjqGoP_Fzipc5FfVV2Whshk7UrXQJK4E9PdmHKZQhz-O6Y58yEF_7BrWocxxwWX4D

## Additional Context

n/a

**Comment by sahithyandev** [comment]
I fixed the issue. Will make a PR.

**Comment by sahithyandev** [comment]
The above commit fixes the issue. As I really don't how or why that works, I am going to stop working on this bug. ✌

**Comment by LuciNyan** [comment]
It looks like working well now. 🤔
