### ISSUE TITLE
accessing tailwind config

### ISSUE THREAD

**Issue by strangecarr** [vercel/satori#342]
Hi, I have some custom colours, as well as special fonts set up in my tailwind.config file. I can't access these when trying to style my OG image - is it possible to access these?

These are the warnings I get when trying to use my customisations:

```
`reem` unknown or invalid utility
`gradient-to-r` unknown or invalid utility
`from-cyan-500` unknown or invalid utility
`to-blue-500` unknown or invalid utility
`clip-text` unknown or invalid utility
`blur-[0.8px]` unknown or invalid utility
```

**Comment by shuding** [comment]
With #340 you can pass custom Tailwind configuration (warning: it's experimental!)
