### ISSUE TITLE
SVG image urls are not working

### ISSUE THREAD

**Issue by searchableguy** [vercel/satori#348]
# Bug report

## Description / Observed Behavior

If you pass a URL to an svg in img tag, it does not work. 

## Expected Behavior

To work since browser also support svg in image tag perfectly fine. 

## Reproduction

[Create a shareable reproduction link for the issue using https://og-playground.vercel.app.](https://og-playground.vercel.app/?share=XVJNT-MwEP0r1qBVL93ES9N0sUoPyyLBgRNIXHJJ40licGIrdvpB1f_OOCEIuM285zfP83GCwkgEAWupdlnLmPNHjdenU4gZq1FVtRds9ofzX7P5CO6V9PUPTCpndX4ktNR4mNAQ_1cdFl6ZlrjC6L5pJzbXqmrvPTYuUNh67CbqpXdelccbQ2Ab_L_T27x4rTrTt_LGaNMRf1GW5acrqR7VGwq2uPwCPX_0knI-oOdz1m5CsHa76ktn1xmslhmMyE7h_p85EMYZZ6slSz-pUmlN-AXnfIKm4bEm7yoVOg4ae5gNZowNdmRoc18zSeKHxSpaXkWXS71IoyuqntxFaTImv9PkLYPNOg6vx4_G9NMxom39dHsyVrCEk9XmDrU2c_ZsOi3XMb0dRaqpmOsK8q29t07EsVUFlYwK08R4yBurMTZ7HYWBAItJNalhDsaGLToQJxjmBOIvTRLGEwGRhETitq9AlLl2OAdszIt6OtpwX34_ZFQn7OK22aIE4bsez-d3)

## Additional Context

Satori version, and any other context about the problem here.

**Comment by wobsoriano** [comment]
Missing `content-type`

<img width="282" alt="Screenshot 2023-01-06 at 6 10 02 PM" src="https://user-images.githubusercontent.com/13049130/211126810-d38e0e93-12ef-48ff-81a4-9c3cbd6c3d34.png">

**Comment by searchableguy** [comment]
@wobsoriano Yeah, I noticed that but it works with other formats when the type is missing from headers. Just not with SVG. 

Also have you tried opening a private browser session and putting the url with network tab there?

I tried to check for the same thing and realized if I reload the image second time in browser, it does not show any type in the headers so I suspect that's not the reason.

**Comment by shuding** [comment]
I think it's not working in the playground only, the website isn't allowed to fetch that image from another origin which is expected:

<img width="1161" alt="CleanShot-2023-01-07-aLwY7Mhu@2x" src="https://user-images.githubusercontent.com/3676859/211168766-e99bc739-9d90-401c-bdfa-8f8c84d7c16a.png">

If it happens when running on the server, we can reopen this issue.
