### ISSUE TITLE
Wrong line breaking

### ISSUE THREAD

**Issue by shuding** [vercel/satori#360]
# Bug report

## Description / Observed Behavior

Not sure why but `fast.!!!!!!!!!!!!!!!!!` should be wrapped into a new line.

## Reproduction

[Playground](https://og-playground.vercel.app/?share=XVHBTsMwDP0VE4R2maDAhFA0dhkIceLABJdd0sZNvaVJlaSMUvXfSTY6wXKJ_V5i-z33rLASGWdzSZ9rA-BDp_Gh71MMUCGpKnCYXGfZxWR6AHckQ3WCSfKNFl1ES41fI5riR3JYBLImcoXVbW1GVmhS5iVg7ROFJqAbqU3rA5Xd0kbQpP7_6VwUW-Vsa-TSausif16W5bFr_PVG38jh9uYP9PGr5S7L9ugwrM0iBUn6UTfUwikyK9twmGXx0WIltmQUCNDWbkEEeEdXoPZgcAeacidcB8GCQoNOBATZGVFTAa8NmmcnmgqoFgo9WAOhwuhKBxSAPJTCh8uz0zO_igPFycabTZltkoOe8Z7t3Wf8Pqpgh_UwPkuJxLxVjJdCe5wyrO2GVl2Tdht2-yzWST481TlKxoNrcRh-AA)

## Additional Context

Satori version, and any other context about the problem here.

**Comment by LuciNyan** [comment]
The cause of this phenomenon looks interesting (and causes many line break issues). Although it may take some time, I would like to try to solve this problem.

**Comment by shuding** [comment]
@LuciNyan thank you! And no rush, let me know if I can help
