### ISSUE TITLE
Consider a new way to load dynamic fonts

### ISSUE THREAD

**Issue by shuding** [vercel/satori#367]
Currently the process of loading dynamic fonts for missing graphemes is, we use a list of RegExps to match that character, and use the first match as the final locale. Then, we go to Google Fonts and load that corresponding Noto Sans with that locale.

The problem is that these RegExps are not accurate. It might be not possible at all to generate RegExps for languages (or too large). For example we have `Han` in both `zh-CN`, `ja-JP`, and `zh-TW` and `zh-HK`, but this is not always correct. In this [example](https://fonts.google.com/?preview.text=%E8%AF%95%E8%AF%95%E7%9C%8B&preview.text_type=custom&query=noto+sans&noto.query=noto) `试` is only available in `zh-CN` but is matched by `Han`.

We can step back and try to load the actual font instead, and check if that character (unicode) is included in that font. For example to render `试`, we matched `["ja-JP", "zh-CN", "zh-TW", "zh-HK"]`. And then, we fetch corresponding Google Fonts CSS such as https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap and check their `unicode-range` to see if `试` is included.

I think this can be a more reliable approach.

[Bug reproduction](https://og-playground.vercel.app/?share=XZDNSsUwEIVfJYzI3RSsP4gEdXN14VrBzd20zaTNNU1Kk3itpU_g2p3v4GPpY5hJragQyJnvkJnMGaGyAoHDuVCPG8OY84PGi3EkzViDqm48Z6vDPN9fZTPcKeGbf0wo1-liiFRqfFoo6SvVY-WVNdGrrA6tWdxCq9rceGwdWWg89ou1Dc4rOaxthIbm_7XLonqoexuMWFtt--jvSSl_psZXt-oZOTs--oXuv3c5zfNEp2ljLknQ6kkw9vn-Gs_H20viB7Ox3JCB7WgTB3yElALws9gN5piAn1AhsAw1cFlohxlga7fqbugoY79LVexD_7luSxTAfR9wmr4A)

**Comment by LuciNyan** [comment]
I'm interested in it! Can you assign it to me? <3

**Comment by shuding** [comment]
Sure, @LuciNyan thank you and feel free to explore this!
