### ISSUE TITLE
Replace tweemoji CDN in @vercel/og

### ISSUE THREAD

**Issue by tiotdev** [vercel/satori#368]
# Bug report

Not sure if this is the right place to report a bug in @vercel/og, I couldn't find a separate repo.

The cdn for tweemoji shut down, please replace it with an alternative CDN: https://github.com/twitter/twemoji/issues/580

## Description / Observed Behavior

The whole page doesn't load if an emoji is requested from tweemoji: "error - TypeError: fetch failed"

I fixed it for my project by using one of the other supported emoji libraries, but since I am using tweemoji in the rest of my project I want to go back to that for consistent looks

**Comment by anurag-roy** [comment]
@shuding That would be great! Currently the whole image fails to load, if there is an emoji anywhere using the default twemoji style.

Slightly related question: Is there a way, I can pass a custom function to Satori which will handle loading of all emojis (say from my custom URL)?

**Comment by shuding** [comment]
@anurag-roy Yes, check the API docs there's an option to load additional assets.

**Comment by shuding** [comment]
Fixed in #371. For `@vercel/og` please upgrade to latest version!
