### ISSUE TITLE
Node/CommonJS support broken

### ISSUE THREAD

**Issue by KiwiKilian** [vercel/satori#369]
# Bug report
Usage in `node@^16` stopped working with `satori@^0.46.0` in CommonJS (no modules). Previously I was able to use satori without any aditional setup.

## Description / Observed Behavior

When calling satori the following error occurs:

```
require() of ES Module /project-path/node_modules/yoga-wasm-web/dist/asm.js from  /project-path/node_modules/satori/dist/index.cjs not supported.
Instead change the require of asm.js in /project-path/node_modules/satori/dist/index.cjs to a dynamic import() which is available in all CommonJS modules.
```

I guess it's due to the changes in https://github.com/vercel/satori/pull/262.

## Expected Behavior

I guess satori should either still work per default in node, or the docs need an update?

If it's only an update to the docs, is this the correct usage in Node with CommonJS?

```js
const { default: satori, init } = require('satori/wasm');
const yoga = require('yoga-layout-prebuilt');

init(yoga);

satori(...)
```

## Reproduction

You can observe the [problem here](https://github.com/KiwiKilian/eleventy-plugin-og-image/actions/runs/3887417922/jobs/6633663448#step:3:70).

## Additional Context

node: 16.18.0
satori: 0.46.0 & 0.1.0

**Comment by nickpell** [comment]
Seeing the same problem.

**Comment by OfficialCRUGG** [comment]
Same issue here with 0.1.1. Downgraded to 0.0.45 for the time being and it works there, but that version still includes other problems, so I need to get on a newer version...
