### ISSUE TITLE
First font declared is being used for the whole image

### ISSUE THREAD

**Issue by anurag-roy** [vercel/satori#370]
# Bug report

First of all, I am using `@vercel/og` with Next.js, so please close this if this is not the right place to report this bug.

## Description / Observed Behavior

I am having this weird behaviour with fonts after upgrading `@vercel/og` from `v0.0.22` to `v0.0.23`.
I load three different fonts in my code like the following:

### Fetch call outside the `handler` function
```typescript
const getSatoshi = fetch(
  new URL('../../assets/Satoshi.ttf', import.meta.url)
).then((res) => res.arrayBuffer());
const getClashDisplay = fetch(
  new URL('../../assets/ClashDisplay.ttf', import.meta.url)
).then((res) => res.arrayBuffer());
const getAloeVera = fetch(
  new URL('../../assets/AloeVera.ttf', import.meta.url)
).then((res) => res.arrayBuffer());
```

### Await promise inside the `handler` function
```typescript
const [satoshi, clashDisplay, aloeVera] = await Promise.all([
  getSatoshi,
  getClashDisplay,
  getAloeVera,
]);
```

### Pass the font data as params
```typescript
{
      width: 1200,
      height: 630,
      emoji: 'fluentFlat',
      fonts: [
        {
          name: 'Satoshi',
          data: satoshi,
        },
        {
          name: 'ClashDisplay',
          data: clashDisplay,
        },
        {
          name: 'AloeVera',
          data: aloeVera,
        },
      ],
    }
```

### Use the different fonts
```tsx
<h1 tw="text-8xl leading-none" style={{ fontFamily: 'ClashDisplay' }}>{title}</h1>
<p tw="mb-16 text-5xl text-gray-900 leading-tight" style={{ fontFamily: 'Satoshi' }}>{description}</p>
<span tw={`text-5xl text-${theme}-600 mr-auto`} style={{ fontFamily: 'AloeVera' }}>{author}</span>
```

Only the first passed font is getting used in the whole image

### Examples

When I am passing Satoshi as the first font

<img width="235" alt="Screenshot 2023-01-12 at 12 16 10 PM" src="https://user-images.githubusercontent.com/53750093/212012379-d6a66824-0697-410a-8769-e48005a7029e.png">

![image](https://user-images.githubusercontent.com/53750093/212008907-5e1563c0-bcd4-4f41-b952-19b3560651d3.png)

When I am passing Clash Display as the first font

<img width="243" alt="Screenshot 2023-01-12 at 12 11 38 PM" src="https://user-images.githubusercontent.com/53750093/212012413-f26b8255-b609-4846-96aa-d24323654095.png">

![image](https://user-images.githubusercontent.com/53750093/212008405-cee89026-2a23-43f8-9729-8576869bc042.png)

## Expected Behavior

This is the expected image

![image](https://user-images.githubusercontent.com/53750093/212017443-2b0e302d-29a7-4cca-8143-93f332d79add.png)

As I said, all the above code works perfectly fine on `@vercel/og` `v0.0.22` and does not after that. Was there any change that I am not aware of?

## Reproduction

I'll try to reproduce this in the Satori playground and update here with a link.
Meanwhile, all source code is available in my repo [here](https://github.com/anurag-roy/og.anuragroy.dev/blob/main/pages/api/index.tsx)

Thanks!

**Comment by shuding** [comment]
Thanks for the detailed reproduction, this is the correct place to open an issue. We will take a look!

**Comment by eeberhart40** [comment]
I'm experiencing the exact same issue after upgrading from v0.0.43 to v0.1.0
I can confirm that multiple fonts were loading in the earlier version

**Comment by eeberhart40** [comment]
lots of changes to the `addFonts` function in the diff between those versions. Haven't honed in on the bug yet but clearly it's defaulting to the fallback, which will always be the first font
https://github.com/vercel/satori/compare/0.0.43...0.1.1

**Comment by anurag-roy** [comment]
`@vercel/og` needs to be updated with `satori v0.1.2`

**Comment by anurag-roy** [comment]
The fix still hasn't reached `@vercel/og` @shuding

**Comment by nsaunders** [comment]
I'm noticing what appears to be the same issue in v0.10.9.
