### ISSUE TITLE
Unsupported OpenType signature in fresh install of @vercel/og

### ISSUE THREAD

**Issue by jonsherrard** [vercel/satori#379]
# Bug report

Getting this error from next.js when I try and load the basic example from go docs.

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/631670/215190631-03907cba-ec8a-4d8f-90aa-d93c40b1330d.png">

What kind of issues did you encounter with Satori?

## Expected Behavior

I've used @vercel/og in a plain Next.js project with custom fonts, inline Svgs... all the bells and whistles, but I can't even get the very basics rendering here. Am perplexed!

## Reproduction

I'm using Next 13.0.4 in a Solito monorepo and the latest version of @vercel/og 

## Additional Context

```sh
error - Error: Unsupported OpenType signature expo
    at Object.parseBuffer [as parse] (webpack-internal:///(middleware)/../../node_modules/@shuding/opentype.js/dist/opentype.module.js:11455:15)
    at bt.addFonts (webpack-internal:///(middleware)/../../node_modules/satori/dist/index.wasm.js:19:19480)
    at new bt (webpack-internal:///(middleware)/../../node_modules/satori/dist/index.wasm.js:19:19079)
    at bu (webpack-internal:///(middleware)/../../node_modules/satori/dist/index.wasm.js:20:28040)
    at Object.start (webpack-internal:///(middleware)/../../node_modules/@vercel/og/dist/index.js:10:2977)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by jonsherrard** [comment]
I see there's been an update to the Yoga that supports `gap`, and I know `Expo` doesn't have that until RN 0.71.... so maybe there's something afoot there....

Flippin monorepos 🤦

**Comment by shuding** [comment]
Can you share the options that you passed to ImageResponse?

**Comment by jonsherrard** [comment]
On phone now, but the basic hello world from next docs

**Comment by shuding** [comment]
Can you try again with `@vercel/og@0.1.0`?

**Comment by shuding** [comment]
Closing as we didn't get similar reports or clear reproduction. Happy to reopen if there's anything we can help.

**Comment by alitnk** [comment]
Facing the same issue. did you find a workaround, @jonsherrard?

**Comment by jonsherrard** [comment]
@alitnk I ended up just deploying a tiny next app for my OG needs only 😂 

If I was near a computer I'd:

- `create-tamagui-app` 
- Add a basic `@vercel/og` router
- Share the repo here with some basic instructions

Maybe @shuding could take a look.

**Comment by jonsherrard** [comment]
@alitnk I saw you got things working! What was the fix>?

**Comment by alitnk** [comment]
> @alitnk I saw you got things working! What was the fix>?

@jonsherrard Yeah! Turned out to be some legacy Webpack code inside `withTamagui()` that we just ended up removing. You can probably move back the OG stuff into your app lol. Just make sure you're on the latest.
