### ISSUE TITLE
Text wrapping in quotation marks to a new line does not work correctly

### ISSUE THREAD

**Issue by vladislavromanov** [vercel/satori#386]
# Bug report

## Description / Observed Behavior

I have a problem when, after the transfer, the quote remains on one line, and the text after the quote wraps to a new line.

## Expected Behavior

The quotation mark, along with the word after it, should be moved to a new line.

## Reproduction
https://og-playground.vercel.app/?share=XZLBbtswDIZfhVAx5JIlWuM4q5DmsG5AB2ynFejFF8WibXWyZMhynDTIu5ey66LtSdT3S_xFUmeWO4VMsK3Sh8wCtOFk8PZ8jjFAhbqsgoDZN86_zOYj7LUK1SemdNsYeSJaGDxONMY_tcc8aGdJy53pajup0ujS_g5Yt1FCG9BP0lPXBl2c7hxBG_0_ynuZ_y-966y6c8Z50q-KonhzpVv_9DMKWF2_Q4-vtaScD_RyyewuBtv2UL6r7DZjm3XGRnLQ2P9wR2IcOGzWkL5JhTaG-BXnfEJT86CWvtSx4ninOc4GM4DBjgwbGSpQdPnvarNY3yyu12aVLm4oe3K_SJNx8zVNnjO22y7j6fGhS3rpGNG0Prs9uEZAwslq98fZEgIeA4RKBirLGGqBzxGCg97LJq4SLPZgtEXI2KPzRsE9GuMytl1SevKZVjZnrokjbJk4s6FJTHynNrLxfzCRxI3CfVcyUUjT4pxh7Z70w6mJnyv0w47yxEH8qveomAi-w8vlBQ

## Problem (SVG tab):
<img width="1296" alt="" src="https://user-images.githubusercontent.com/63917524/216775262-6a910380-6167-4a4b-ae5b-a60c6ecbdfec.png">

## Should be (HTML tab):
<img width="1296" alt="Screenshot 2023-02-04 at 18 20 15" src="https://user-images.githubusercontent.com/63917524/216775322-90b14690-017e-4bd8-a40d-0bcfcc2a5691.png">

**Comment by LuciNyan** [comment]
This PR(#372) may fix the issue.
