### ISSUE TITLE
Text-wrapping does not support CJK Characters

### ISSUE THREAD

**Issue by syahzuan** [vercel/satori#389]
# Bug report

Text-wrapping does not support CJK Characters. 

## Description / Observed Behavior

Chinese characters overflow and did not break into a new line.

## Reproduction

https://og-playground.vercel.app/?share=tZJPTsJAFMavMhlj2CCMUIpMgIVoogtXkrjpprTTdnDaadopUJquvYFHMDHRPQcyxGP4prUE2bvqm9_XN9_7MwV2pMswxWOXr6wIoVTlgk2KQscIBYz7gaKodUnIeatdwzV3VXDCXJ7Gws6BeoJtGqrjG54wR3EZgeZIkYVRo9qC-9G9YmGqJRYpljTSMksV9_KZBBhp_7_ywnae_URmkTuTQiagn3med3CFrEe-ZRT1e0fo6bcXk5CKlqUVTXUwTlf-UWcTCw8HFq7JirP1tdwAI4ig4QCZB8njQgA_I4Q0qBkeCu3E57pjnRNvWpUZQpUdGMa2CpALyQ_9YWcw6vQGom92RnC7cdcxjfpwYRpbC0_HXf13XWgXKq0j2Nap21zGFBkErKZfu8_968t-9_H9_vYf8bgL_lBI88VtLGO94xTTAldTxPQK5ozrB4SpoQ8uW2Q-pp4tUtbGLJRLPs9j_frUujrBPXpTt-GCuZiqJGNl-QM

## Additional Context

Was testing out @vercel/og

**Comment by lili21** [comment]
https://og-playground.vercel.app/?share=tZJPTsJAFMavMhlj2CCMUIpMgIVoogtXkrjpprTTdnDaadopUJquvYFHMDHRPQcyxGP4prUE2bvqm9_XN9_7MwV2pMswxWOXr6wIoVTlgk2KQscIBYz7gaKodUnIeatdwzV3VXDCXJ7Gws6BeoJtGqrjG54wR3EZgeZIkYVRo9qC-9G9YmGqJRYpljTSMksV9_KZBBhp_7_ywnae_URmkTuTQiagn3med3CFrEe-ZRT1e0fo6bcXk5CKlqUVTXUwTlf-UWcTCw8HFq7JirP1tdwAI4ig4QCZB8njQgA_I4Q0qBkeCu3E57pjnRNvWpUZQpUdGMa2CpALyQ_9YWcw6vQGom92RnC7cdcxjfpwYRpbC0_HXf13XWgXKq0j2Nap21zGFBkErKZfu8_968t-9_H9_vYf8bgL_lBI88VtLGO94xTTAldTxPQK5ozrB4SpoQ8uW2Q-pp4tUtbGLJRLPs9j_frUujrBPXpTt-GCuZiqJGNl-QM

it looks like some character doesn't render correctly.
