### ISSUE TITLE
<table> doesn't work as expected

### ISSUE THREAD

**Issue by kvidelov** [vercel/satori#395]
# Bug report

## Description / Observed Behavior

``<table>`` , ``<tr>``, ``<td>`` and ``<th>`` are not behaving as regular HTML would.

```html
 <table>
    <tr>
      <th>Company</th>
      <th>Country</th>
    </tr>
    <tr>
      <td>Alfreds</td>
      <td>Germany</td>
    </tr>
</table>
```
results into:

![Screenshot 2023-02-10 at 2 09 27 PM](https://user-images.githubusercontent.com/58029419/218100329-1c1678e5-f772-458a-a772-0f4ebc60a1c4.png)

## Expected Behavior

Table headers, rows and cells behave the same as regular HTML

![Screenshot 2023-02-10 at 2 14 08 PM](https://user-images.githubusercontent.com/58029419/218100939-d75bd2f0-cb67-4e0c-b03e-11b4cd4cddea.png)

## Reproduction

https://og-playground.vercel.app/?share=XZDBDoIwEER_pdmLlyZ68GAaJDHG-AMevYBdaBVaUpYgIfy7CxiJ9DSz07x2toeH1wgKIkrSAkVNXYHHvk-TxysPvnFaiU1rLOFGCoM2N8SD_W5XvXnQWk2G_WHywxDfnRAzaZLjiSj89OhMfPZllbgu2rJeJ42j8J-wWQBrmI5PRRZQ13xLr5IrhnJ-Zkl-MBbfXy4KJPiKrHc1qB6mbqC4moS5OCjuLUFj2uSgsqSoUQKW_mlvXTXukNrJMSfzji5lihoUhQaH4QM

**Comment by shuding** [comment]
This is expected, Satori only supports `display: flex` and `display: none` ([documentation](https://github.com/vercel/satori#css)). All other display modes for table elements, such as `display: table` will not work.
