### ISSUE TITLE
Specific SVG doesn't render

### ISSUE THREAD

**Issue by shuding** [vercel/satori#397]
# Bug report

## Description / Observed Behavior

[This SVG](https://og-playground.vercel.app/?share=zVVdb5swFP0rlqspq1SBzVcCSvawblondepD106aIrUEDHFLAIETmkX577s2IXw0654m7QFhn3t977nHvvYOB1nIsIenId_MU4RKsU3YbLeTY4SWjMdL4aERJeTd6KIGKx6K5QALeZkn_hbQKGEvDSrHn3jBAsGzFGxBlqxXaWP1Ex6nXwVbldLEUsGKxvS0LgWPtpcZgKnM3zcv_OA5LrJ1Gl5mSVaA_SyKomNWWHXLfzEPmUYH-nGoxSFEofv9PP1Qm6flJq5H4MqTZDbHaZayOW7ADWfVx-wFcIIIohP1teZaptkOFIGgNaZU6kMvqyQtIcZSiNzT9aqqtMrUsiLWDUKILkkcQh54AbOVXz43k2OiOe6lR4iHkOmYByG56i7lQmZbl6y4zf2A3aR3Zaemdq-V-_dtDoqN_CRf-iMlTuNWV_Iqp1KjC2z7wLEGqCLgRZAwFMg1LvigQDqr0UHvRQJ7CtOiwfVWA13ya6ex4jvbPa6L5P0ZPX_cv07VAqjN2gMbAl2wz6VrkbQm4y7W8oOkuS-WXfcQ3L9Ry9VsMkHUHmu2ce24GrUMZFtXtnVPDVtzx1eOo1FqOvdgMyemc01NV3NdF1HH0iaWfUktUzNNE-aG5lALUcuBkNJONOrYMO-m-HmyGqVS7vNUkIeEp8wvHgzXgI-c_7Ee2bJvhqJvheqc07HRNxzP0gCXW0Sp3QflFtnWaZJTPW7HIYvKLv2a25fCDzncG92Q8QH7e3Oopprjk8INuFNJnrgD1JCoZWnDopQ3hX0c4Mof9rWHd6qS15TIcujaLFfXHvhXSy6AdW_zGr8sikqm7gpwOLVIYjdQOxeHzu2fAb2v4r_Ud3iaTulrQBmv9TWINnYHyiuF--emkZc42mT8vws81TvneSqfBRgDyDfwxxc4y-VzWmJvh1U7YW8CTxquew57lpyEbLGOsRf5SckuMFtlT1xe8PDQi0rNII58FD-vFizEnijWbL__DQ) doesn't render in Satori.

**Comment by yisibl** [comment]
resvg does not currently support the mask-type property, would you be interested in implementing it upstream?

**Comment by shuding** [comment]
It doesn't render even in SVG so I think it's a Satori issue.

**Comment by Jackie1210** [comment]
looks like resvg has just supported `mask-type`, will learn this property first before I can fix it. hhhhh😝
