### ISSUE TITLE
Update satori of of @vercel/og?

### ISSUE THREAD

**Issue by amzfcy** [vercel/satori#407]
# Feature Request
Update satori of of @vercel/og

## Description
The lastest release of satori is v0.3.1, but in vercel/og is v0.0.44.

## Additional Context

You can add a shareable link using https://og-playground.vercel.app, or any other context that helps explaining this feature request here.

**Comment by shuding** [comment]
`@vercel/og@0.2.0` is released and using `satori@0.4.0` under the hood 👍

**Comment by tomy0000000** [comment]
@shuding Do you happen to know if `@vercel/og` is open-sourced, or where can I submit issues?

**Comment by shuding** [comment]
@tomy0000000 we haven't open sourced it yet so feel free to open issues in this repo! 🙏

**Comment by Nos43ratu** [comment]
@shuding will it be open source in the future?

**Comment by shuding** [comment]
@Nos43ratu Yep we plan to move it to this repository and make it a monorepo.
