### ISSUE TITLE
Build error with new Next.js 13 route handlers

### ISSUE THREAD

**Issue by seanislegend** [vercel/satori#410]
Using this package with the new [Next.js 13 route handlers](https://beta.nextjs.org/docs/routing/route-handlers) results in a build error/dev runtime error.

## Description / Observed Behavior

Next.js app does not build because of missing export from @vercel/OG.

## Expected Behavior

No build time errors.

## Reproduction

Available in this repo https://github.com/seanislegend/next-13-route-handler-vercel-og-error
- `/src/app/og/route.tsx` uses the new app directory route handlers. This works.
- `/src/pages/api/og.tsx` uses Next.js page API routes. It works.

## Additional Context

- Next.js version 13.1.7-canary.21
- @vercel/og version 0.1.0 and 0.2.0-beta.0

<img width="1321" alt="Screenshot 2023-02-19 at 18 32 38" src="https://user-images.githubusercontent.com/1477984/219976504-8df12771-83e8-4b84-b72e-a1df81947d74.png">
<img width="1506" alt="Screenshot 2023-02-19 at 18 34 27" src="https://user-images.githubusercontent.com/1477984/219976503-326e3058-cf8c-4c6c-a451-93ec78af87f8.png">

**Comment by AndrewIngram** [comment]
Tried digging into this, but all I can really determine is that any imports from Satori seem to fail when using the edge runtime in the Next route handlers, using the edge runtime in the old pages dir has no issues.

**Comment by shuding** [comment]
Spent some time debugging and it turned out to be caused by https://github.com/vercel/next.js/issues/43732 — Satori's ESM build contains `__esModule` as well due to its vendors. I'll look into fixing that.
