### ISSUE TITLE
Match word-break attributes to CJK characters to browsers

### ISSUE THREAD

**Issue by hiddenest** [vercel/satori#414]
# Bug report

## Description / Observed Behavior
There is a difference with browsers when you specify word-wrap or text-wrap attributes for CJK characters.

`word-break: keep-all`

![open-graph-1](https://user-images.githubusercontent.com/8682478/222165901-aad00011-e792-4c39-a150-b41d2bd34382.png)

`text-wrap: balance` (additional, maybe linked with `word-wrap`)

![open-graph](https://user-images.githubusercontent.com/8682478/222165990-14290999-5ef8-45b1-9182-0a023bb23644.png)

## Expected Behavior
It would be nice if the browser rendering matched the rendering in satori.
(Of course, I agree that it is difficult to implement and may have a low priority)

`word-break: keep-all`

<img width="526" alt="스크린샷 2023-03-01 오후 11 13 29" src="https://user-images.githubusercontent.com/8682478/222166082-92ceb665-482c-4130-aa28-da897a916fa8.png">

Here's a list of breakpoints that depend on property values by language:
* `word-break: normal`
  * non-CJK: spaces, hypen(-)
  * **CJK: syllables**
* `word-break: break-all`
  * non-CJK: syllables
  * CJK: syllables
* `word-break: keep-all` (applies to CJK only)
  * non-CJK: spaces, hypen(-)
  * **CJK: spaces, hyphens '-', other symbols**

References from [here](https://wit.nts-corp.com/2017/07/25/4675), which is written in korean.
also it provides some [example](https://codepen.io/witblog/full/gRrdPR/) too.

## Reproduction

[Reproduction Link](https://og-playground.vercel.app/?share=XVGxTsMwEP2VixHqEom0SAVFwIKQuoPE0sWpL6nBjaPEpS1RhiCQ2KvuMFQMDBVDx07s6UcEJvgInESh0Ml379nv3fPFpCcZEpscMX7T9QEiNRF4HMdFDdBH7vWVDY2mZe02zAoccab6WxjjUSDoRKOuwHGNOrR37YVy6LNTKWSo2R3XdSs2Sbr-SVHUztveG6NDywp-NQEGNPS4r_H2P9iRIcPCoxmMIZKCMwiRbXhX-uqc36K-cdD6-1DhWF2GNNCEQwX1e1hzxYwA5ZQAHRRCGvCxevqcrwz4nj1-PcwMyNNpfjfN09c8fc7ThQHZS_aWLdZptlzfZ0sDOlSI97lRRt3TWbVcfRKTyEBx6UfEjkkZl9jNlmWZpPp5Yrf3dcPQGXrEdqmI0CQ4kFf8YhIUa1OjstNCRbyzgYOM2CocYpL8AA)

## Additional Context

Satori 0.4.0

**Comment by LuciNyan** [comment]
Good catch! <3

**Comment by LuciNyan** [comment]
Hi @hiddenest! Just to let you know, satori currently doesn't support 'word-wrap', but the issue with 'word-break: keep-all' has been fixed in this [PR](https://github.com/vercel/satori/pull/415).

**Comment by hiddenest** [comment]
Wow! That's what I've wanted 🙏 
Thanks @LuciNyan :) (Hope it merged & released as soon as possible...)
