### ISSUE TITLE
Problem to render emojis

### ISSUE THREAD

**Issue by mybess00** [vercel/satori#418]
# Problem to render emojis

I'm trying to render custom images for specific graphemes as specified in the documentation. But the image does not load.

Documentation: 
```
await satori(
  <div>Next.js is 🤯!</div>,
  {
    ...,
    graphemeImages: {
      '🤯': 'https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/svg/1f92f.svg',
    },
  }
)
```

Result: 
![Image - 2023-03-05T162047 004](https://user-images.githubusercontent.com/69021807/222986719-a6d8081d-6aa5-4d1e-beb8-d7d99f8a89e4.png)

**Comment by shuding** [comment]
Are you rendering it on the server or inside the browser (is so are there any error logs in the console?)
