### ISSUE TITLE
Not supporting RTL

### ISSUE THREAD

**Issue by mzaien** [vercel/satori#420]
# Bug report

## Description / Observed Behavior

Satori does not support RTL direction for Arabic, Urdu, etc... it shows the text reversed 

<img width="1249" alt="CleanShot 2023-03-06 at 17 54 30@2x" src="https://user-images.githubusercontent.com/43112535/223145929-bcfa1c49-d72d-4982-9141-deb1185b7e33.png">

## Expected Behavior

it should show the image with right direction 
## Reproduction

[demo](https://og-playground.vercel.app/?share=XZJLbsIwEIavYk1VsaHglhBaC1j0IbWLrlqpm2wCdoJbJ44Sh1fEDpWj0F3XvQncpmNCEKBI8cz32_PbYxcw1FwAgy6XYy8mJDMzJXpFYWNCRkKGI8NI7ZrSy1q9hBPJzeiMcZklyp8hDZSYVtTGjzIVQyN1jNpQqzyKK9VXMoxfjIgyK4nYiLSSPvPMyGD2oBHG1v9UHvjDrzDVecwftNIp6hdBEBxccdWbnAtGWjdH6GN_FpfSHV0s7J_LtFd4kBrlAYK-Zd1sHB4dtedBp-1BScZSTO71FBkllHTaxD1IgVQK-QWltEJVN0nkp6G0LbBrkmlt776zQ8PENyPCcfFrq9No3zVu2qrlNu6wuvPccJ0yuXKduQf9btPOLjfaxJ2WEV7fudu7ThhxKFqdnrJvRGYI2ay3q-1ys7bBtx3-Nj-bX0yW-K26TayIpasR6qATe40ZsAJ2fQF2i62E8o0Ac2zCxSAPgQW-ykQdRKQ_5fsssQ_MTHYZ1rGX8RQNBAdm0lwsFv8)

## Additional Context
Satori version: latest ,
There is another issue for Arabic I'll report in another issue to have more concise issue

**Comment by shuding** [comment]
Thanks for creating the issue! We already have #74 that tracks the RTL feature so I'm going to close this one.
