### ISSUE TITLE
Satori crashes if the text only consist of Arabic letters

### ISSUE THREAD

**Issue by mzaien** [vercel/satori#421]
# Bug report

## Description / Observed Behavior
Satori crashes if I wrote Arabic only, if I wrote anything before it in english it will not crash but will be filliped because it [does not support RTL ](https://github.com/vercel/satori/issues/420)

![CleanShot 2023-03-06 at 17 52 02](https://user-images.githubusercontent.com/43112535/223147876-6a5d123d-59d8-4c82-9956-8ab51cc8a7a6.gif)
atori/issues/420)

## Expected Behavior
Arabic should not crash satori 
## Reproduction

[demo](https://og-playground.vercel.app/?share=XZJNbsIwEIWvYg2q2FBwIYRiAYvSSu2iqyJ1k03ATjB14ihx-IvYtWfpAXoZuE3HhCBgk8x8z-PnGbuAmeYCGAy4XHoxIZnZKDEsChsTMhcynBtG6g-U3tUbJVxJbuY3jMssUf4GaaDEuqI2fpapmBmpY9RmWuVRXKm-kmH8ZkSUWUnERqSVtMgzI4PNWCOMrf-1PPVnX2Gq85iPtdIp6rUgCM6uWPUht4KRTvsCfZ56cSk90t3OfrlMh4UHqVEeIBhZNsiW4UWrQw96XQ9KspRi9aTXyCihpNcl7lkKpFLIa5TSClXTJJGfhtKOwNYk6_rJ_WiHholv5oRj8Xun1-z2m-2u6rjNPu7uvDZdp0zuXWfrwWjQsqvLg7bwpGWE13frNtEJIw5Fq-suR_u_w_f-9_AzaGEVlld_aIBO7FVlwAo49g7sEccF5TsA5tiEi2keAgt8lYkGiEgv5GST2EdkVscM97EDf4mmggMzaS52u38)

## Additional Context

Satori version : latest

**Comment by Othmanosx** [comment]
I'm having the same problems actually, completely unable to generate anything with Arabic letters

**Comment by shuding** [comment]
Should be good now: [playground](https://satori-playground-git-shu-jhxy.vercel.sh/?share=XZJNbsIwEIWvYg2q2FBwIYRiAYvSSu2iqyJ1k03ATjB14ihx-IvYtWfpAXoZuE3HhCBgk8x8z-PnGbuAmeYCGAy4XHoxIZnZKDEsChsTMhcynBtG6g-U3tUbJVxJbuY3jMssUf4GaaDEuqI2fpapmBmpY9RmWuVRXKm-kmH8ZkSUWUnERqSVtMgzI4PNWCOMrf-1PPVnX2Gq85iPtdIp6rUgCM6uWPUht4KRTvsCfZ56cSk90t3OfrlMh4UHqVEeIBhZNsiW4UWrQw96XQ9KspRi9aTXyCihpNcl7lkKpFLIa5TSClXTJJGfhtKOwNYk6_rJ_WiHholv5oRj8Xun1-z2m-2u6rjNPu7uvDZdp0zuXWfrwWjQsqvLg7bwpGWE13frNtEJIw5Fq-suR_u_w_f-9_AzaGEVlld_aIBO7FVlwAo49g7sEccF5TsA5tiEi2keAgt8lYkGiEgv5GST2EdkVscM97EDf4mmggMzaS52u38). Thanks for reporting!

**Comment by mzaien** [comment]
> Should be good now: [playground](https://satori-playground-git-shu-jhxy.vercel.sh/?share=XZJNbsIwEIWvYg2q2FBwIYRiAYvSSu2iqyJ1k03ATjB14ihx-IvYtWfpAXoZuE3HhCBgk8x8z-PnGbuAmeYCGAy4XHoxIZnZKDEsChsTMhcynBtG6g-U3tUbJVxJbuY3jMssUf4GaaDEuqI2fpapmBmpY9RmWuVRXKm-kmH8ZkSUWUnERqSVtMgzI4PNWCOMrf-1PPVnX2Gq85iPtdIp6rUgCM6uWPUht4KRTvsCfZ56cSk90t3OfrlMh4UHqVEeIBhZNsiW4UWrQw96XQ9KspRi9aTXyCihpNcl7lkKpFLIa5TSClXTJJGfhtKOwNYk6_rJ_WiHholv5oRj8Xun1-z2m-2u6rjNPu7uvDZdp0zuXWfrwWjQsqvLg7bwpGWE13frNtEJIw5Fq-suR_u_w_f-9_AzaGEVlld_aIBO7FVlwAo49g7sEccF5TsA5tiEi2keAgt8lYkGiEgv5GST2EdkVscM97EDf4mmggMzaS52u38). Thanks for reporting!

Thanks a lot
