### ISSUE TITLE
Text immediately after ⚡️ not rendered

### ISSUE THREAD

**Issue by jamaljsr** [vercel/satori#422]
# Bug report

## Description / Observed Behavior

When the High Voltage emoji (26a1) is immediately followed by a non-space character, satori eliminates the next word. If a space is added in between the emoji and the word, then it works fine. If this emoji is placed immediately after a word without a space, a rectangle box is displayed instead of the emoji.

This html:
```
  <div>⚡Hello⚡</div>
  <div>⚡ Hello ⚡️</div>
  <div>Hello ⚡</div>
  <div>⚡ Hello ⚡there</div>
  <div>⚡ Hello ⚡ there</div>
  <div>⚡Hello there</div>
  <div>Hello⚡ s</div>
  <div>Hell⚡ o</div>
  <div>H⚡ello</div>
  <div>Hello ⚡✨🚀</div>
```

produces this output:

![image](https://user-images.githubusercontent.com/1356600/223413267-976bbb4b-43a1-451e-9007-c70a106a9785.png)

## Expected Behavior

The ⚡️ emoji should be able to be immediately preceded and followed by word characters.

## Reproduction

https://og-playground.vercel.app/?share=fZJLTsMwEECvYg1C3VQifISQVbopSLAGiU03aTxJXBy7ih1KiCJxA_YVEmLHEThPLwBHwJOSqq3arjx-b8a_cQWREQgcekI-DTVj1pUKL6uKYsZSlEnqOOscB8Fhp7uAUylcusGEtBMVlp7GCp9bSvGVzDFy0mjvIqOKTLc2VDLRtw4zSwq1w7xV48I6GZcD46Gm_df1KIwek9wUWgyMMrn3B3EcL3f1VXfyBTk7PVlBD_93OQ-Chtb1UPcpoKv357PPG1TK-LF3RGDVsEYxH_18v23opdpX5lLMcV8C25GxSNgm29Myu0UQN5vcQ6rZdf75-9fvx-y11e0IXTAT6p8FXkHTe-AX_g1h8TmAn9FE4KhIgMehstgFzMxY3pcT-llu2sz8OtSF62yEArjLC6zrPw

## Additional Context

I also noticed that this issue occurs with the Small Orange Diamond emoji 🔸 (1f538) as well.

**Comment by LuciNyan** [comment]
Hi @jamaljsr!
Thank you so much for taking the time to report this detailed issue. We've identified the problem and currently working on a solution. It may take some time. Appreciate your patience.

**Comment by jamaljsr** [comment]
Hi @LuciNyan, thanks for confirming the issue. Appreciate the update. 

I've worked around it for now by injecting spaces around those two emojis, so it's not urgent.

**Comment by jamaljsr** [comment]
Confirmed the 0.4.3 release solves the problem. Thank you for the quick turnaround 🙏.
