### ISSUE TITLE
Some fluent emojis are not displaying correctly

### ISSUE THREAD

**Issue by yutakobayashidev** [vercel/satori#425]
# Bug report

## Description / Observed Behavior

The keyboard emoji (⌨) does not seem to display correctly for fluent emoji, it displays correctly for Twemoji.

![image](https://user-images.githubusercontent.com/91340399/224027920-51089167-f102-4e3f-a9e1-67655a851c6c.png)
![image](https://user-images.githubusercontent.com/91340399/224028119-39378700-01ca-464f-b2e3-7ba753743f95.png)

This issue may be related to Variation Selector-16.

Accessible URL:

https://cdn.jsdelivr.net/gh/shuding/fluentui-emoji-unicode/assets/%E2%8C%A8%EF%B8%8F_color.svg

Inaccessible URL:

https://cdn.jsdelivr.net/gh/shuding/fluentui-emoji-unicode/assets/%E2%8C%A8_color.svg

## Expected Behavior

Need to display fluent emoji correctly

## Reproduction

https://og-playground.vercel.app/?share=XZLBUoMwEIZfJRPH6aXS2AK1GdqD1Rk9eLIzXrhQCJAaEgZCW8rwBj6Iz-WTuAHp1J7YfP9u_uwuDQ5VxDDFXsT3vkSo1LVgy6YxMUIp40mqKRrdE3I7GvfwwCOdXrGIl7kIaqCxYMeBmviJFyzUXEnQQiWqTA5qIHgiXzXLSiMxqVkxSLuq1Dyu1wqgNP7_5W0QfiaFqmS0VkIVoN_EcXx2hap3fmIUzaYX6OOvF5eQjratL1cm8Mp9ctHZ0sdzx8c92XN2eFRHYAQRNHeQe5ZiLgTwG0LIgIbhoSwoEm46NjX5cdSZIdTZgWEe6BRFUPw2m1vOwpo6YuZaC7jdfrFcuz_cufbJxytvYrL7h07gpX0E27p226icIpuA1ern69ubQArkDl88xio3aygxbXDXKKYPMArc7xhT2xwitq0STONAlGyMWaZ2fFPn5geJRQU7gGvMLJ-zLYsw1UXF2vYX

**Comment by GavanWilhite** [comment]
[Ballot box with ballot](https://github.com/microsoft/fluentui-emoji/tree/main/assets/Ballot%20box%20with%20ballot)

Also doesn't show up.

FWIW it looks like fluent doesn't include country flags. I don't know if there's an easy way to do a fallback for these?

**Comment by GavanWilhite** [comment]
Woah, I don't know what's going on, but now it seems to be? 
I'm doing this: 


  ```
    {
        width: 1024,
        height: 1024,
        emoji: hasEmojiNotInFluentSet ? 'twemoji' : 'fluent',

```

And now it seems to be doing what I want it to.... but in a way that makes no sense. It's mixing fluent and twemoji

<img width="1216" alt="Screenshot 2023-03-15 at 3 01 45 PM" src="https://user-images.githubusercontent.com/2085119/225454034-aa7a8fe5-a3b8-4101-9048-0b6d644e69a2.png">

Some sort of odd caching behavior?

**Comment by jeetiss** [comment]
I create the fix that removes `Variation Selector-16` in fluent emoji, so this should fix current issue https://github.com/shuding/fluentui-emoji-unicode/pull/1

**Comment by shuding** [comment]
I just merged your PR @jeetiss (thanks!) and hopefully it will solve this.
