### ISSUE TITLE
emoji-regex crashes since 0.0.43 (browser usage)

### ISSUE THREAD

**Issue by drcmda** [vercel/satori#451]
# Bug report

## Description / Observed Behavior

```error
(0 , Uo.default) is not a function
```

it tries to require the default export of emoji-regex. im guessing since it is a mjs/module it can't be required any longer?

## Reproduction

https://codesandbox.io/s/satori-html-tailwind-in-threejs-forked-z6njms?file=/src/Satori.js

## Additional Context

Satori version 0.0.42 works, since then it fails.

**Comment by LuciNyan** [comment]
Hi @drcmda!

Thank you for providing the link to help reproduce the issue. However, I am unable to access the link you provided :(  
Is it possible for you to provide another link or additional details that I can use to investigate the issue further?

**Comment by Jackie1210** [comment]
maybe we can add a `need reproduction` tag @shuding

**Comment by Samirox66** [comment]
The same error occurred. I'm using kotlin/js so I am not sure I can make reproducation. But I can show where error occurred
![image](https://user-images.githubusercontent.com/70467187/233996657-6949a9f4-839c-4c91-a3b7-f2493b40e0e2.png)
![image](https://user-images.githubusercontent.com/70467187/233997468-e2cf58bf-0d0f-4305-ab41-a7e77207fc24.png)
Don't know how useful it is

**Comment by drcmda** [comment]
@LuciNyan sorry codesandbox defaulting boxes to private now is killing me. it's public now.

**Comment by shuding** [comment]
It looks like a bundling issue of Codesandbox, not sure what exactly happened but I can't repro locally or manually putting that built file on Codesandbox. I think due to the number of environments that Satori supports (Node/Edge/Worker/Browser + native/wasm) and the complicated situation of bundlers nowadays, I'd just pre-bundle `emoji-regex` in the build.
