### ISSUE TITLE
clip-path doesn't seem to be respecting the "at x and y" positioning

### ISSUE THREAD

**Issue by romellogoodman** [vercel/satori#466]
# Bug report

## Description / Observed Behavior

When using the new `clip-path` functionality I expected the position of the clip to either be relative to the container or able to be specified.

## Expected Behavior

I expected to be able to control where the clip was being positioned or to have it automatically detected. Instead it seems to be centering based on the height and width of the container and not also applying the containers x and y position

## Reproduction

https://og-playground.vercel.app/?share=nVRta9swEP4rQhDSgpM4r21NEti6QvthY9CyfckX2b44amXLyEqc1OS_706um6ahK9RgWXqe0z2nu5MrHukYeMCnsdwsMsYKu1MwqyqaM7YCmaxswNp932-1vRosZWxX77BYFrkSO0SXCrYNamFrvymZZIhHkFkwDSMIvbOQFifU47qwcrm71ghmpH1Mk_8f0kBkpXZ-tVqn2Vv2rxE5EpkucdIQoYieEqPXWXytlTbIlytp4ZS-S0UCSBsRS6E6CX0xgLNImkgBE5YNxvnWDR7DU6wsmuzYoOUxa0RW5MKgOfNb5x772McF-aDhEx-n8d3LZwoPk48e3NjYRErmv4UrTS10NvZbJIZW9J63yW6_X2RzmjQVf1_zj4r536J9WjaSZcwJo3SxSZp9dYvNqkvfWdCzkVB-19vZgvvMxyyxyXjBG3IplUImVJiRA9ocgaXCJJL6gjZibl6EX6VRPMccsRh9_BxedMdX3cFYDSfdK5QZ3XYno3rRmYyeF3w-7ZF1E3YP465z18PkfTGLS8xQXcSRfwySA9e4JhXqsAE73DWsO_IBrk_6oLHXhwdHSmZw-3Jr-93LV9x1-30uIlLIDXTeXo7j4oTzP2AiUOwmToD9Altq8zTthUcnb77c4zqnq1jwoOLu18CD_sD3PV5XlgcTWsQQrhMeLIUqwOOQ6kf5sMvpz2NLt0JHlISbNISYB9asYe9xK0K0qMPh-38

## Additional Context

Satori version, and any other context about the problem here.

**Comment by Jackie1210** [comment]
@romellogoodman  thanks for your feedback and i've found the cause, i will fix it later.
