### ISSUE TITLE
HTML entities are not escaped when using `embedFont: false`

### ISSUE THREAD

**Issue by osener** [vercel/satori#474]
# Bug report

When rendering SVGs that contain ampersand (`&`) character, pass-through mode with `embedFont: false` results in incorrect rendering due to HTML entity escaping issues.

## Reproduction

[Code Sandbox](https://codesandbox.io/p/sandbox/pensive-cloud-4gki76?file=%2Fpages%2Fapi%2Fhello.tsx&selection=%5B%7B%22endColumn%22%3A35%2C%22endLineNumber%22%3A13%2C%22startColumn%22%3A35%2C%22startLineNumber%22%3A13%7D%5D)

See the endpoint [`/api/hello`](https://4gki76-3000.csb.app/api/hello) for the issue.
 
You can see when `embedFont: false` is set and a div containing ampersand `&` is rendered, the text doesn't pass through to SVG correctly

![Screenshot 2023-05-04 at 18 20 39](https://user-images.githubusercontent.com/111265/236264878-bbc87322-fff2-4436-832a-2303f48648ed.png)
![Screenshot 2023-05-04 at 18 20 50](https://user-images.githubusercontent.com/111265/236264887-6b39f300-e8e1-413e-b8db-ad23eb337c51.png)

Resulting SVG:
![hello](https://user-images.githubusercontent.com/111265/236265692-2a32aab9-7571-494b-a46d-b4b81e8923fa.svg)

**Comment by Jackie1210** [comment]
This issue is releated to `resvg-js`/`resvg`. The result satori generate is:
```html
<svg width="100" height="100" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><mask id="satori_om-id"><rect x="0" y="0" width="94" height="19" fill="#fff"/></mask><text x="0" y="15.48289183222958" width="36.7734375" height="18.75" font-weight="normal" font-style="normal" font-size="16" font-family="serif" fill="black">Hello</text><text x="36.7734375" y="15.48289183222958" width="3.9609375" height="18.75" font-weight="normal" font-style="normal" font-size="16" font-family="serif" fill="black"> </text><text x="40.734375" y="15.48289183222958" width="9.9453125" height="18.75" font-weight="normal" font-style="normal" font-size="16" font-family="serif" fill="black">&</text><text x="50.6796875" y="15.48289183222958" width="3.9609375" height="18.75" font-weight="normal" font-style="normal" font-size="16" font-family="serif" fill="black"> </text><text x="54.640625" y="15.48289183222958" width="39.46875" height="18.75" font-weight="normal" font-style="normal" font-size="16" font-family="serif" fill="black">world</text></svg>
```

but it result an error when generate img by `resvg-js`
<img width="777" alt="image" src="https://github.com/vercel/satori/assets/14737221/99d939bf-385a-4b68-b1c8-81120e7767a8">

It shows error even on latest version of `@resvg/resvg-js` @shuding  CC @yisibl

**Comment by RazrFalcon** [comment]
This has nothing to do with `resvg`. `&` must be escaped.

**Comment by Jackie1210** [comment]
@osener should work now! Give it a try~
