### ISSUE TITLE
overflow:hidden not being respected when using transforms

### ISSUE THREAD

**Issue by saihaj** [vercel/satori#481]
# Bug report

## Description / Observed Behavior

I am using absolute positioning, when using `transform` with `overflow:hidden` on parent, content seem to overflow

What kind of issues did you encounter with Satori?

## Expected Behavior

How did you expect Satori to behave here?

Content should not overflow

## Reproduction

https://og-playground.vercel.app/?share=ZZNvi5wwEMa_SgiUa0HX1VW3K73CUaQctBS2pW9uyxHNqGmjkTjuny773S9RZNe7VzHPMxlnfpOcaa440ITumk9c7Ake7ne0kHAkLOuU7BEIqtZ9Wsft8Q_RoqzQfYqWw0b1DQfuBke5o593DSE2g10J6fAk4f58HneEcNG1kp0Scmdz3zmTnrH8XzkkMtahEgg3ntIc9JZx0XfG9U0FV7MCW4qRw9AUc9UPgmP1Vm5VJ1CoxjgaJEOxv_mR2oMupDoYsxKcQzNZl4tdh9ZMc6IupxNMosGU24NuWylUO8NvtAaAMzST85rJrKqJ9rUqQiQUtsNV9O5WHWZgZDdYz3QzJqMGy5mYKURVW3r-TL_i82ecbgC-NlCzpiuUttm0Qobw3o85lB-uQSOvoVedGwwVYtslnmem_1_iRsZ9GdSLXKqeF1o1uGgAPaZRdOj2rVSMd164CfxVtlq7-SZeuuEqCtwsC2IXVsUyjzbrNWfgbdNv6cPP9PnLj9_p9vnx-8PX1AuWoR9GvtvA4bFmJSzappzge-P1NIXszde4Uoeq1tLvaHKmQ9s0-RgGDh3h0CTaxA7lkPUlTVD34FCo1V_x69TaB1PIHho0WQrTSVpnwMeoi0ORZSagAmkuldKS08sL

## Additional Context

If I try in simple browser this is what I would expect to see 
![image](https://github.com/vercel/satori/assets/44710980/c386fb90-683b-4a40-9921-16ed8cba7737)

**Comment by 2hu12** [comment]
`5. overflow: hidden and transform can't be used together.` this has been documented in the README, so it's not a bug I think.
