### ISSUE TITLE
Error: `fetch` is required to be polyfilled to load images.

### ISSUE THREAD

**Issue by uncenter** [vercel/satori#489]
# Bug report

## Description / Observed Behavior

I have a script to generate preview images using Satori that works locally but errors in production on Netlify when trying to fetch image URLs:
```
Error: `fetch` is required to be polyfilled to load images.
```
How best should I approach fixing this? The error appears [here](https://github.com/vercel/satori/blob/341bfab3326da507accc550d0197ffed90d8e3ac/src/handler/image.ts#L220) in the image handler but I cannot figure out how to supply a new `fetch` function to `globalThis.fetch`.

## Reproduction

I'm actually using this as part of the build process for my static site: https://github.com/uncenter/uncenter.org

However, I believe you can reproduce this by trying to run this on Netlify anywhere.

**Comment by uncenter** [comment]
I guess you can just use a later Node version with built-in fetch (which is what I'm now doing)... but there should still be a way to provide an alternative?

**Comment by shuding** [comment]
As `fetch` is the standard way to load data in all runtimes (browser, Node, workers, etc) we don't plan to support other I/O methods at the moment. There're two work arounds, you can polyfill fetch globally, or pass a base64 data URL or Buffer/ArrayBuffer as the image's `src` so Satori won't fetch the resource.
