### ISSUE TITLE
`radial-gradient` without shape throws error

### ISSUE THREAD

**Issue by imranbarbhuiya** [vercel/satori#496]
# Bug report
using `radial-gradient` without shape throws error
## Description / Observed Behavior

What kind of issues did you encounter with Satori?
Use `{ backgroundImage: 'radial-gradient(#4E98D5,#CF684A)' }` to see the error
## Expected Behavior
it should work like browser does
How did you expect Satori to behave here?
same as browser
## Reproduction

Create a shareable reproduction link for the issue using https://og-playground.vercel.app.
It works in playground but not in my nextjs app. https://codesandbox.io/p/sandbox/hopeful-mirzakhani-gdz45h

gradient-parser returns `undefined`  orientation https://github.com/vercel/satori/blob/1c9e463fc652c030c431f51bc4bc23a4d93ecef7/src/builder/background-image.ts#L319 here so using `[0]` on undefined is throwing 
```sh
[1] - error TypeError: Cannot read properties of undefined (reading '0')
[1]     at Sn (file:///D:/Discord/Sofi-Site/node_modules/next/dist/compiled/@vercel/og/index.node.js:15350:46)
[1]     at kt (file:///D:/Discord/Sofi-Site/node_modules/next/dist/compiled/@vercel/og/index.node.js:15475:48)
[1]     at Ot (file:///D:/Discord/Sofi-Site/node_modules/next/dist/compiled/@vercel/og/index.node.js:15574:15)
```

## Additional Context

Satori version, and any other context about the problem here.
using bundled vercel or with `next@npm:13.4.3`

**Comment by Jackie1210** [comment]
Can you share a reproduction link? I tried and it is okay.[link](https://og-playground.vercel.app/?share=XZBRT4MwEMe_CrnFTBOMqLhgM03MNpM9a-ILL4Ue0Fla0hYRCd_dlonRPd3d73-96_0HyBVDILBm_COVQWBsL_BhGHweBBXysrIkWF5H0dkyPMKOM1udMMZNI2jvaCHwc6Y-33KNueVKOi1Xoq3lrFLBS7m3WBsvobSoZ-nQGsuLfqMclH7_fzmj-XupVSvZvqYlOl1Txqm4LH10reeLeHefbO_CxeZ5lcRPF78_chNf-Jd7cnvzB7393LmKoomOYyofU7m-cq64CCGoxt9ggAww3Q8kcb1wNAhI7AuGWVsCKagwGALW6sBf-8a7a7upcnP8tl2dIQNidYtjCJZmrqNCIVSntGAwfgM)

**Comment by imranbarbhuiya** [comment]
Just notices there's a new nextjs release `^13.4.4` and after upgrading, it's working now. Thanks for the quick reply

**Comment by imranbarbhuiya** [comment]
Sorry, idk how it worked last time but it's not working again.
![image](https://github.com/vercel/satori/assets/74945038/3d8ea900-b702-400d-85a1-c6264be633d4)

**Comment by imranbarbhuiya** [comment]
> Can you share a reproduction link? I tried and it is okay.[link](https://og-playground.vercel.app/?share=XZBRT4MwEMe_CrnFTBOMqLhgM03MNpM9a-ILL4Ue0Fla0hYRCd_dlonRPd3d73-96_0HyBVDILBm_COVQWBsL_BhGHweBBXysrIkWF5H0dkyPMKOM1udMMZNI2jvaCHwc6Y-33KNueVKOi1Xoq3lrFLBS7m3WBsvobSoZ-nQGsuLfqMclH7_fzmj-XupVSvZvqYlOl1Txqm4LH10reeLeHefbO_CxeZ5lcRPF78_chNf-Jd7cnvzB7393LmKoomOYyofU7m-cq64CCGoxt9ggAww3Q8kcb1wNAhI7AuGWVsCKagwGALW6sBf-8a7a7upcnP8tl2dIQNidYtjCJZmrqNCIVSntGAwfgM)

dk how but It works in playground. I said in original message too

> It works in playground but not in my nextjs app. gradient-parser returns `undefined`  orientation https://github.com/vercel/satori/blob/1c9e463fc652c030c431f51bc4bc23a4d93ecef7/src/builder/background-image.ts#L319 here so using `[0]` on undefined is throwing

**Comment by Jackie1210** [comment]
https://github.com/Jackie1210/satori-issue-496 I created a minimal reproduction and it works fine with `@vercel/og`, maybe you should provide minimal reproduction in your situation.

**Comment by imranbarbhuiya** [comment]
go to https://codesandbox.io/p/sandbox/hopeful-mirzakhani-gdz45h?file=%2Fpackage.json%3A12%2C5 and open `/test` link

**Comment by imranbarbhuiya** [comment]
I also added the cause of the bug. 
![image](https://github.com/vercel/satori/assets/74945038/98fafca5-4df6-4961-a1b5-b2e24b6cb8b9)
if u dont add the shape, `gradient-parser` gives `undefined` orientation. And https://github.com/vercel/satori/blob/1c9e463fc652c030c431f51bc4bc23a4d93ecef7/src/builder/background-image.ts#L319 is using `[0]` on undefined so it's throwing

**Comment by Jackie1210** [comment]
> go to https://codesandbox.io/p/sandbox/hopeful-mirzakhani-gdz45h and open `/test` link

it show the error when use `ImageResponse` from `next/server`, it works fine with `@vercel/og`. not familiar with `next`, it seems that `next` use a compiled `@vercel/og`, maybe not latest version? CC @shuding

@imranbarbhuiya you can use `@vercel/og` directly to work around it.

**Comment by Jackie1210** [comment]
> I also added the cause of the bug. ![image](https://user-images.githubusercontent.com/74945038/241525413-98fafca5-4df6-4961-a1b5-b2e24b6cb8b9.png) if u dont add the shape, `gradient-parser` gives `undefined` orientation. And
> 
> https://github.com/vercel/satori/blob/1c9e463fc652c030c431f51bc4bc23a4d93ecef7/src/builder/background-image.ts#L319
> 
> is using `[0]` on undefined so it's throwing

@imranbarbhuiya I remember that I did fix some bugs in this lib, original `gradient-parser` is outdated.

**Comment by imranbarbhuiya** [comment]
Yeah, I checked nextjs and it recently updated `@vercel/og` but it's not released in canary/stable yet. I checked the content and found a change related to orientation is present there. So waiting for next canary release. Thanks for helping
