### ISSUE TITLE
Debounce on onchange function when writing code in Editor.

### ISSUE THREAD

**Issue by Shubhdeep12** [vercel/satori#514]
# Feature Request

## Description
It doesn't feel good to have errors while writing code in the editor.
Can we have Debounce on onchange function in the editor?

What do you want to add to Satori, and why?

For better UX

## Additional Context

You can add a shareable link using https://og-playground.vercel.app, or any other context that helps explaining this feature request here.

**Comment by Shubhdeep12** [comment]
It's not a big change.
Please confirm if this is a valid enhancement.
WOuld love to add this.

THanks

cc @shuding

**Comment by shuding** [comment]
I think it's nice to have real-time update for every keystroke to show how fast Satori is @Shubhdeep12 (personally love it) 😃. If you're willing to contribute to the project, would you mind taking a look at the bug that the playground itself doesn't load on mobile Safari?

**Comment by Shubhdeep12** [comment]
Yeah, ok will check that. @shuding 
We can close this one. 
Thanks for replying.

**Comment by Shubhdeep12** [comment]
Is there a issue created for the same?

**Comment by shuding** [comment]
> Is there a issue created for the same?

I don't think so, feel free to open one for it!
