### ISSUE TITLE
fontStyle italic not rendering correctly

### ISSUE THREAD

**Issue by ppjjzz** [vercel/satori#517]
# Bug report

## Description / Observed Behavior

What kind of issues did you encounter with Satori?

## Expected Behavior

How did you expect Satori to behave here?

## Reproduction

Create a shareable reproduction link for the issue using https://og-playground.vercel.app.

## Additional Context

Satori version, and any other context about the problem here.

**Comment by shuding** [comment]
Please make sure to add a reproduction, thanks!
