### ISSUE TITLE
Unable to set `"min-content"` as `maxWidth`

### ISSUE THREAD

**Issue by RubenSmn** [vercel/satori#521]
# Bug report

## Description / Observed Behavior

I tried setting the `maxWidth` to `"min-content"` and got the following error: 

```js
Invalid value min-content for setMaxWidth
```

## Expected Behavior

I expected this to work since there are no mentions about it not being supported in the [CSS section on what is supported](https://github.com/vercel/satori/tree/2e8dcb486f3dadeb6fc2e8790cb822a72893a21a#css).

## Reproduction

https://og-playground.vercel.app/?share=XVC7bsMwDPwVgosXF8mQSUi7FAXauQGyZJEt2laqhyHJdVzD_17JctDHRPKOPB5uxtoKQoZHIT8vBsCHSdHjPKceQEjfKz4xKBpFt6LMaEey7QKDw36_IaMUofsNcCVb8xZI-3hbkwnk7tfXwQfZTM82giaq_KMrXn-0zg5GRGoipeyYqWW5mKfUHPu8-dcqQBMV3-UXxbuDI30XzMR581xUVokfSvPbOXsvtDQPdTZVZDp9BFh_Apwo2jYtvJKj1cWuj8xxF3OLFUu0fZDWeGQzrnEgS3FgDmsbBFVDi6zhylOJpO1VnqY-5R_GdYo6ye2LrkggC26gpcTAq7jRrVlYpwQu3w

You can click **HTML (Native)** to see the expected result.

**Comment by shuding** [comment]
We need to add a note to the README that `min-content` and `max-content` are not supported. I don't think this can be implemented easily at the moment.
