### ISSUE TITLE
can support webp image input?

### ISSUE THREAD

**Issue by ppjjzz** [vercel/satori#539]
# Feature Request
support webp image input
## Description
support webp image input
What do you want to add to Satori, and why?
support webp image input
## Additional Context

You can add a shareable link using https://og-playground.vercel.app, or any other context that helps explaining this feature request here.

**Comment by Jackie1210** [comment]
It should work like [doc](https://github.com/vercel/satori#images) said.

**Comment by Jackie1210** [comment]
duplicated https://github.com/vercel/satori/issues/273

**Comment by ppjjzz** [comment]
> It should work like [doc](https://github.com/vercel/satori#images) said.

https://og-playground.vercel.app/?share=XZHLTsMwEEV_JRqEuonyainUatkUFqxBYhMJJfHEcevYUew0DVH-HbsPBF1YnjnX4_Fcj1AoikBgTfkhlZ6nzSBwM44u9rwKOasM8WZxFN3P_DPsOTXVDaNcNyIbLC0FHq_UxS-8xcJwJa1WKNHV8qpmgjP5ZrDWTkJpsL1Ku04bXg5bZaF0_f_LeVbsWas6SbdKqNbqd2VZ_na1Ve_8G4k3T_6gz8ssyyg60WlK5XMq17xmnm6LTQqVMY0mYdjMy2OwZ1YIClWHhyTcd0x1vFAyTKJ4Fa2SJI4je9FqsXyIH4Ndw76sG0e7XBz0mDcpnI3ajJZOFycvSej6htZxu4MPqnH-aCAjnEqAPNk3wrkEyMIlFPOOASkzodEHrNWOfwyN-znTnzJ7j5vytc6RAjFth5MPJsvtiQqFUL1qBYXpBw

not working
