### ISSUE TITLE
Support `numberOfLines`

### ISSUE THREAD

**Issue by amannn** [vercel/satori#556]
# Feature Request

## Description

React Native supports [`numberOfLines`](https://reactnative.dev/docs/text.html#numberoflines), can this be supported in Satori too?

**Comment by Jackie1210** [comment]
@amannn I think what you want is `line-clamp` and it is supported by satori. Since `numberOfLines` is not a css feature defined by spec, satori would not implement it.

**Comment by amannn** [comment]
That's right, `line-clamp` would probably be the user-facing API since satori has a CSS API. However, it seems like `line-clamp` isn't supported yet as far as I can tell: [playground](https://satori-playground.vercel.app/?share=NVK7chsxDPwVDFO4uVE0TorMjZPGcZcuSacGInEnJCRBk6BlW6N_N2jJHV5c7C5xcl4CudndlV0GaPoS6fvpNGKAgiFwXme43U6Xyh79_7VKz-FeotQZbj4ty3Jz7S6S9Te_0gxfbq-lyJnuI6ZiIKNyPu_yjxH8kkoJuLSeIAwsaKyAiXQCL7mRV9JeAQMXbt5oAEW2ZqNgD4C4tyQBlFKxx5w9Bw49K3SFiHuDB9ILNEHCNSNg5MeOG_irQJmTYUPiETxZimmCx84NsjStPQA9U_WsqCwZejQRXi7IY4gbj03vkFxsGAiNeDJOchFgq3QDPwckdiXg2o3JRStnqFQqHSgHqibcCk8Se7F1ZHRMKVBrBJ5j_HDIBHVY-sqokAch-6BqSa8beHj2VJTMsMbmgXiP5G3O98IBDdVkZShVOFAeLg6nbKnvseDQDbIs7BkhUKM6uknioIHDIDY72tXXnja7fPe52De6yUkZ_jQ3n9yRgx7c_G27ndyBeD2om7-OJNC-r25eMDaaHCX5x39eyrg6Pb5nhjNu5yHtKbjZ3Kfz5BT3NnGgGOUoNQZ3fgM).

Am I missing something?

**Comment by Jackie1210** [comment]
<img width="862" alt="image" src="https://github.com/vercel/satori/assets/14737221/d085c8ed-4bdb-4568-ad2e-80cfed838a1c">

I think there are two ways:

1. [`-webkit-line-clamp: 3`+`display:-webkit-box`+`text-overflow: ellipsis`+`-webkit-box-orient: vertical`](https://satori-playground.vercel.app/?share=XVPLjlMxDP0VKwh1c1vKwAJdDWxgdkgsgN1schPf1kwSZxJn2lL133H6QIhd_Dr2OXaOxrFHM5r7_JgAqhwCfjwe-xvAU83BHkZYLHc4PZEsJ94vhkswW-8pbUa4W189k3VPm8It-c8cuGjZq3meb_kzJ_lOv3GEd3dX11_YQAmXLtiYF4p3je7Iy1ZB3q7Xr28gW6TNVv5zCu7l2wuWOfBOQxgC5Ur1Fv53-CUXwiTaZaEFQs6GRc86nR7Tp_74ygUjaH2L4DsLqCRgI8oAjlNFJyitgPWUqToVADCQBit6LQCkViN7nSlmLabkyJNvSaAJBDspPKBcoBGi3SQLNtBzsyv4KYCJomJDpP54UdPGAZ4bVUhcpTQPuMfiSKwQJ2hBRXN8Qe5JVKl3OkNS1mRAq4NHnYkvBLSVrOBLh7RNEKg0neTClRIUzAW3mDwWJa6OFw4tazvUcZQpYK0IjkK4KaSEGsxtQ1Yg9YH0NIoarazgYe8wC6pglVQDds6i0zzXMnmrqEorQS5MXteiKnaltKlrIdvOG3ieyZEFjxVLj0bW_SrDLhCpHPWqa4urx3T_JusazWA4d32qGY_mfEdm_LBeD-ZyP2Z83w2PU9uYcbah4mAw8i_6ccj9M8jubClOv9qHOKE3o6qPp8GInTRjq1fGOy7Bm9Mf)

2. [lineClamp+block](https://satori-playground.vercel.app/?share=VVI9kxMxDP0rGjPMNTshHBTMzkFzXEcHdGm0tnYjzl9ny5cLmfx35GxS0Fmy9PTek07GJkdmNA95FwGqHD19PZ36G8BxzR6PI9xNPtnnu2FNZ3SO4zLC_faamdA-LyW16B6TT0Ub3s3zfKufU5Sf_JdG-HR_TXmO9OgxZAW5pg7sZK-dH7fb97fOPfGyl_-S5_MufuuPH6lQAM61BXB9KlQWwEAygE2xkhWSVgAdZ65WCQN51s9KThuAuNWQHAiFrM0cLTt2LQo0AY-TwgPJCk0QcIkI6Pml4QZ-C1DkoNgQuD9eNcQwwEvjCjFVKc0BvVGxLCicIjSvcm1akXsRV-6TLpCctRgIlXhQTmkVoKNkA987JDYh4NKUyaqVIxTKhfYUHRUVronX5FvWcaR0VClQrQSWvb85pIIazG1hFIidkK6yaNDKBp7eLGUhNayyepCsRbJaZ1tmh4qqsiLkkthR7C52p3SobT5j1w1pntkygqNKpf-G5DsN7Aax2lGvvraw2cWHD1nXaAaTcvenmvFkLidgxi_b7WDW1Zvxcw8cTW0x44y-0mAopD_865j72crhEilOv7KnMJEzo7pP58EITlqxJ-_TIRXvzPkf)

**Comment by Jackie1210** [comment]
> <img alt="image" width="862" src="https://user-images.githubusercontent.com/14737221/271869540-d085c8ed-4bdb-4568-ad2e-80cfed838a1c.png">
> I think there are two ways:
> 
> 1. [`-webkit-line-clamp: 3`+`display:-webkit-box`+`text-overflow: ellipsis`+`-webkit-box-orient: vertical`](https://satori-playground.vercel.app/?share=XVPLjlMxDP0VKwh1c1vKwAJdDWxgdkgsgN1schPf1kwSZxJn2lL133H6QIhd_Dr2OXaOxrFHM5r7_JgAqhwCfjwe-xvAU83BHkZYLHc4PZEsJ94vhkswW-8pbUa4W189k3VPm8It-c8cuGjZq3meb_kzJ_lOv3GEd3dX11_YQAmXLtiYF4p3je7Iy1ZB3q7Xr28gW6TNVv5zCu7l2wuWOfBOQxgC5Ur1Fv53-CUXwiTaZaEFQs6GRc86nR7Tp_74ygUjaH2L4DsLqCRgI8oAjlNFJyitgPWUqToVADCQBit6LQCkViN7nSlmLabkyJNvSaAJBDspPKBcoBGi3SQLNtBzsyv4KYCJomJDpP54UdPGAZ4bVUhcpTQPuMfiSKwQJ2hBRXN8Qe5JVKl3OkNS1mRAq4NHnYkvBLSVrOBLh7RNEKg0neTClRIUzAW3mDwWJa6OFw4tazvUcZQpYK0IjkK4KaSEGsxtQ1Yg9YH0NIoarazgYe8wC6pglVQDds6i0zzXMnmrqEorQS5MXteiKnaltKlrIdvOG3ieyZEFjxVLj0bW_SrDLhCpHPWqa4urx3T_JusazWA4d32qGY_mfEdm_LBeD-ZyP2Z83w2PU9uYcbah4mAw8i_6ccj9M8jubClOv9qHOKE3o6qPp8GInTRjq1fGOy7Bm9Mf)
> 2. [lineClamp+block](https://satori-playground.vercel.app/?share=VVI9kxMxDP0rGjPMNTshHBTMzkFzXEcHdGm0tnYjzl9ny5cLmfx35GxS0Fmy9PTek07GJkdmNA95FwGqHD19PZ36G8BxzR6PI9xNPtnnu2FNZ3SO4zLC_faamdA-LyW16B6TT0Ub3s3zfKufU5Sf_JdG-HR_TXmO9OgxZAW5pg7sZK-dH7fb97fOPfGyl_-S5_MufuuPH6lQAM61BXB9KlQWwEAygE2xkhWSVgAdZ65WCQN51s9KThuAuNWQHAiFrM0cLTt2LQo0AY-TwgPJCk0QcIkI6Pml4QZ-C1DkoNgQuD9eNcQwwEvjCjFVKc0BvVGxLCicIjSvcm1akXsRV-6TLpCctRgIlXhQTmkVoKNkA987JDYh4NKUyaqVIxTKhfYUHRUVronX5FvWcaR0VClQrQSWvb85pIIazG1hFIidkK6yaNDKBp7eLGUhNayyepCsRbJaZ1tmh4qqsiLkkthR7C52p3SobT5j1w1pntkygqNKpf-G5DsN7Aax2lGvvraw2cWHD1nXaAaTcvenmvFkLidgxi_b7WDW1Zvxcw8cTW0x44y-0mAopD_865j72crhEilOv7KnMJEzo7pP58EITlqxJ-_TIRXvzPkf)

CC @LuciNyan

**Comment by amannn** [comment]
Oh right, thank you so much! That works for my use case.

**Comment by LuciNyan** [comment]
Hi @amannn! I wanted to let you know that Satori now fully supports the [lineClamp](https://www.w3.org/TR/css-overflow-4/#line-clamp:~:text=5.1.-,Limiting%20Visible%20Lines%3A%20the%20line%2Dclamp%20shorthand%20property,-Name%3A) feature from the CSS4 draft specification. This means that if needed, you also have the ability to customize block ellipsis rather than relying on the default browser behavior.

Please let me know if you have any other questions!

**Comment by VityaSchel** [comment]
> Hi [@amannn](https://github.com/amannn)! I wanted to let you know that Satori now fully supports the [lineClamp](https://www.w3.org/TR/css-overflow-4/#line-clamp:~:text=5.1.-,Limiting%20Visible%20Lines%3A%20the%20line%2Dclamp%20shorthand%20property,-Name%3A) feature from the CSS4 draft specification. This means that if needed, you also have the ability to customize block ellipsis rather than relying on the default browser behavior.
> 
> Please let me know if you have any other questions!

It would be great if it was also available with flex, like in browser
