### ISSUE TITLE
Mask image always applied to root instead of element

### ISSUE THREAD

**Issue by pjeweb** [vercel/satori#565]
# Bug report

## Description / Observed Behavior

If you apply a mask image to an element, it gets applied relative to the root node (top left most) instead of the offset position of the element.

## Expected Behavior

I expected the mask to be applied to the elements bounds.

## Reproduction

[Reproduction](https://og-playground.vercel.app/?share=3VRNb9swDP0rhIDAGxbUTgP0ICw7rO2hpx22Yy5yRNtqZMmQ5DhZkP8-yh9Nlu1QoD3VgGHykaIe-Swd2cZKZJx9lWq3NgA-HDSujsdoA1SoyipwSBZZNkvmA9gpGaorTCrfaHEgtNC4n9BoPyiHm6CsodjG6rY2U1RoVZqngLWPITQB3RR6bn1QxeHeEmji_n-HC8J_qt_IYXE3QrnYbEtnWyMp2zphSpyyS9FwuM1673Ram2_RmPq97higsV6NfEXuiXF4qQQQLNUaSsVHY0Hszv40r9vsjI3juoT-P62rJkqH-DIrgFr47VMtSmp6zVqnP0kRBFcRSf2u_LKv9Xy2vCcTdgq773a_SjLIgFSKbwKUYPwqqUJoeJp2XXfTLW-sK1NilsUSyWz5SBWiXFAorVdJVylqfuhgFfVOxg5HJx1WxMVkfV6zcyfWSXTxJ2n2QENUEhzKZAhHEQB6GQAeLHrorNv2qqQky5v1IW5XCl0i76lRrtuLzT-qRD-MPkAjXFBCkxXF8q9V6z2nHel9-GH358HY8M-ZmL5szmwTD4Bn_Mh6Lowv4jDZQIbxu-hIzNuS8UJoj3OGtX1Wvw5NvOtD13tUKF6kj3WOkvHgWjzNWRA5ZVSotSUCWrLTHw) using the same simple mask (just a 100x100 rect) to three elements. One positioned absolute to the top left, one slightly offset (only part of it is visible) and one centered on the canvas being hidden completely.

## Additional Context

n/a

**Comment by MattIPv4** [comment]
👋 FYI this fix still hasn't made it into @vercel/og + next/og -- I couldn't find the source for @vercel/og (and next/og just bundles a compiled version of @vercel/og). Filed https://github.com/vercel/next.js/issues/72940 to track that.
