### ISSUE TITLE
Custom fonts not rendered correctly

### ISSUE THREAD

**Issue by pixelass** [vercel/satori#577]
# Bug report

## Description / Observed Behavior

When rendering a custom font, several issues occur (also see #413 #215).
Typefaces that use ligatures or intensive kerning demonstrate this issue very well (see example below)
It seems like certain information of the ttf are simply ignored by Satori, making Satori extremely unreliable when custom fonts are used.

## Expected Behavior

I expect satori to render google fonts (from ttf imports) exactly as they are rendered via `next/font/google`

## Reproduction

Please visit https://satori-bug.vercel.app/
Please check the source code here: https://github.com/pixelass/satori-bug

What we see in the image below:

- line-height is incorrect (most likely a kerning issue)
- ligatures do not work
- kerning does not work

Left: HTML/CSS | Right: Satori
![image](https://github.com/vercel/satori/assets/1148334/581de524-9e4f-49fd-beba-1817b398e84f)

## Additional Context

```
"@vercel/og": "^0.5.20",
"next": "14.0.3",
```

**Comment by shuding** [comment]
Fixed by #599.
