### ISSUE TITLE
Error with linear-gradient

### ISSUE THREAD

**Issue by edwardhorsford** [vercel/satori#581]
# Bug report

I'm using Satori by way of the [Eleventy OG plugin](https://github.com/KiwiKilian/eleventy-plugin-og-image).

## Description / Observed Behavior

I'm getting an error with the following css:
```css
background-image: linear-gradient(
      to bottom right,
      transparent 50%,
      #e70565 50%
    ),
    linear-gradient(#e70565, #e70565),
    linear-gradient(to top left, transparent 50%, #e70565 50%);
  background-repeat: no-repeat;
  background-size: 10px 68%, calc(100% - 20px) 68%, 10px 68%;
```

The error is: `e70565, #e70565): Missing comma before color stops`

Confusingly, the same css with a different colour does not error:

```css
background-image: linear-gradient(
          to bottom right,
          transparent 50%,
          #b393d3 50%
        ),
        linear-gradient(#b393d3, #b393d3),
        linear-gradient(to top left, transparent 50%, #b393d3 50%);
      background-repeat: no-repeat;
      background-size: 10px 68%, calc(100% - 20px) 68%, 10px 68%;
```

however, it does not render correctly:
![Screenshot 2024-01-09 at 14 38 10](https://github.com/vercel/satori/assets/2204224/f7074720-3637-4926-81bd-588d1accf325)

## Expected Behavior

When rendered on screen (not Satori), these linear gradients add up to look like this:
![Screenshot 2024-01-09 at 14 37 10](https://github.com/vercel/satori/assets/2204224/698a9c41-9805-4704-ad2b-58cbe0ac347b)

## Reproduction

[Error with color stops](https://og-playground.vercel.app/?share=bVNNb9swDP0rhIIiLeCkWhI7rZH2sG7AehgwbAV2yUWxZVudLBmS8tUg_32UZWddUsOwqfdIPomkDiTTOScpWeRis1QA1u0lfzgcvA1QcVFWLoXhJ0qvhlEAtyJ31RmWC9tItke0kHzXo97-IgzPnNAKuUzLda16lklRqmfHa-sprhw3PfW6tk4U-yeNoPL6_9Mrlv0pjV6r_ElLbZAfFEVxUsWoX-KNpzCdvIN-d2dJKG3R43GpHr2xsJvy3ckelmQeL0lANoJvP-sdYhQozGNITlQhpER8QCntob54UDNTCn9iH9Pshq0YQCuHgg1zFeQY_H06H8f340ksp8n4HrPPvo2TWViMktnbkjwubr132Ogt7jRY2K2zVv2rSTi7b0-zg_Z7WbfnmpXeSQrFmRmVhuUCS3ztNKy0c7oG46sVOcOUbZhBDmJ6FQ34nMZJ7O2bCM6jOzaCzkCX7vlAx-kGJC9cBOcifXircrn3n7zhzA-F0iPT2pc-pxpgCZI7TJkxmV37iYURTBC9CXDvcJnhh7aiG1u_S2y8z9KOYbDbAnlzGKapay7ASyUs4MvAeneV8dA87Bn69H8SEd14AUvSA2knj6R3OJskXDqSzvwi56t1SdKCScsjwmv9Kl72jb-xbtuuMI-f7q_1iuckdWbNjxFxbIUeFZdSb7WROTn-BQ)
[No error, but rendering incorrectly](https://og-playground.vercel.app/?share=bVPfb5swEP5XTo6qtBJJWUhIg9I-rJu0Pkyatkp7yYsBA-6MjWznV6P87ztjSNukCMH5--7us-_OB5KpnJGELHO-WUkAY_eC3R8OzgaoGC8rm8DwSxheDQMPbnluqzMs56YRdI9oIdiuR539jWuWWa4kcpkS61r2LBW8lE-W1cZRTFqme-plbSwv9o8KQen0P9Ipzf6VWq1l_qiE0sgPiqI4qWLUH_7KEogm76C_3VniMGzR43ElH5yxNJvy3cnuV2Q-WxGPbDjbflU7xEIIYT6D-EQVXAjEB2EY9lBfPKipLrk7sYtpdsNWDKCVQ8GG2gpyDP4ZzcezxXgyE1E8XmD26Y9xPPWLUTx9XZGH5a3z9hu9xZ16C7t11qq3mvizu_Y0O2i_l3V7qmnpnASXjOpRqWnOscTXVkGqrFU1aFetwGoqTUM1cjALr4JBGi2iPHL2TQDn0R0bQGegS_d8omNVA4IVNoBzkT68Vbnc-2_WMOqGQqqRbu1Ln1MNsATxHabMqMiu3cTCCCaI3ni4d7jM8EsZ3o2t2yU23mVpx9DbbYGcOfTT1DUX4LniBvClYJy7zJhvHvYMffo_CYhqnIAhyYG0k0eSO5xN4i8dSaZukbN0XZKkoMKwgLBavfDnfeNurN22K8zjpvt7nbKcJFav2TEglqboUTEh1FZpkZPjfw)

**Comment by CryptoGraffe** [comment]
this errors for me as well:

```
background: 'linear-gradient(0.05turn, #6c47d7 5%, #1e1f21 70%)',
```

I get:

```
 Error: .05turn, #6c47d7 5%, #1e1f21 70%): Missing comma before color stops
```

**Comment by Jackie1210** [comment]
@CryptoGraffe @itsjavi #562 will fix your problems once merged
