### ISSUE TITLE
justifyContent: "end" not supported

### ISSUE THREAD

**Issue by Huilensolis** [vercel/satori#618]
# Bug report

## Description / Observed Behavior
if you use styles to set up a flex layout with JustifyContent: "end", it crashes

It works if you use "flex-end" instead.

## Expected Behavior

I would like it if it had support for `justifyContent: "end"`, since it's more like the browser CSS. As the browser supports it, typescript and most IDE provide autocompletion for the value "end", which can lead to a bad developer experience if it's in the autocompletion but does not work.

## Reproduction

[playground link for reproduction](https://og-playground.vercel.app/?share=XZJNb4MwDIb_SuRp6oW12UrpFnU97EPaDjttUi9caGMgXUgQhH6q_30OjKrqCed57byxzRFWViIImEm1iQ1jtdtrfD4efcxYjirLnWCDe85vB0EHt0q6_IpJVZc62RNNNe566uM3VeHKKWtIW1ndFKZXE60y8-mwqL2ExmHVS-umdirdv1qCxvujkb22TFa_WWUbI1-tthWJN2mani2p5FsdULDxwwVa_DcScd7S0yk2cx_M6k120dZzDNNJDB3ZKNy-2B0xzjibTlh0llKlNfEbznmP-smxIqky5dv1NeVu0Jox1tqRYZm4nEkq_hpPh5On4cNEj6PhE90efgyjsDvcReEhhvls5LO7h47opV1Eq7p2-7GlYCEnq_kHam0DtrCVlrMR5VJR_4UAbOmXUYM4QtsxiEeaCXSbBhH6g8Rlk4FIE11jAFjYtfrZl_43cdv2RPf4qb4XS5QgXNXgKQCXLCkj9_Zbbw6nPw)

**Comment by shuding** [comment]
Thanks for opening the issue. Satori uses Yoga to handle layouts, which doesn't support `end` (only `justify-end` is allowed):

https://www.yogalayout.dev/docs/styling/justify-content

Unfortunately we can't easily have that addressed inside Satori.
