### ISSUE TITLE
Inline SVG's not vectorized

### ISSUE THREAD

**Issue by heggemsnes** [vercel/satori#623]
# Bug report

## Description / Observed Behavior

Exported SVGs that contain SVGs aren't usable in i.e. Figma or Illustrator since the inline SVG is formatted through <image/>.

## Expected Behavior

Inline SVG's inside the created SVG should be regular vectors

## Reproduction

Export the regular "Hello world" and add it to Figma / Illustrator. The Vercel triangle dissapears.
https://og-playground.vercel.app/

## Additional Context

Not sure if this is "working as intended" but being able to use the created SVG's in practice would make this tool really useful. Our current case is to create a "logo generator" where multiple departments can create their own logo based on a default logo.

**Comment by shuding** [comment]
This is expected, otherwise Satori needs to ship with a rasterizer (but the scope of it is still XML-to-XML conversion). To work around it you can rasterize the SVG first using libs like Resvg.

**Comment by erxclau** [comment]
@shuding I'm curious about the initial decision to convert `svg` elements into `image` elements. You mentioned in #86 that nesting SVGs doesn't sound standard. You also mentioned in #98 that the `image` embedding is closer to browser behavior. 

However, a simple nested SVG example like the following seems to work across the major browsers for me (Chrome, Safari, Firefox on macOS):

```html
<svg width="100" height="100">
    <rect width="100" height="25" fill="blue"></rect>
    <svg width="50" height="40">
        <rect width="10" height="10" fill="red"></rect>
     </svg>
</svg>
```

The above example also works both on Adobe Illustrator and Figma. Were there specific problems with nested SVGs that you ran into? The current `image` conversion for nested SVGs doesn't work in these external programs. 

The rasterization suggestion is not preferable in my use case as I'd like access to the vectors in Illustrator/Figma.

I also wonder if something like replacing nested SVG elements with `g` elements with transforms and scales would be sufficient to inline vector elements without having nested SVGs.

**Comment by benjick** [comment]
@erxclau 

> Now using a workaround with some client-side DOMParser manipulation to extract the SVG element from the image href.

Could you expand on this? I wanna embed our logo (svg)

**Comment by erxclau** [comment]
@benjick 

Here's a relevant [code snippet](https://github.com/erxclau/yagr/blob/92aeec3858449e6721c93c1fba91edfc3b19e52d/app/components/satori/Client.tsx#L13-L56) from a larger project I have:

```ts
const svg = await satori(node, options);

const parser = new DOMParser();
const document = parser.parseFromString(svg, "image/svg+xml");

const svgElement = document.querySelector("svg");
if (svgElement === null) {
  return svg;
}

const images = svgElement.querySelectorAll("image");

if (vectorizeNestedSVGs) {
  const prefix = "data:image/svg+xml;utf8,";

  for (const image of images) {
    const href = image.getAttribute("href");
    if (href === null || !href.startsWith(prefix)) {
      continue;
    }

    const data = decodeURI(href);
    const svgString = data.slice(data.indexOf(prefix) + prefix.length);

    const replacementDocument = parser.parseFromString(
      svgString,
      "image/svg+xml"
    );

    const replacementSvg = replacementDocument.querySelector("svg");

    if (replacementSvg === null) {
      continue;
    }

    for (const { name, value } of image.attributes) {
      if (name === "href" || name === "mask" || name === "clip-path") {
        continue;
      }

      replacementSvg.setAttribute(name, value);
    }

    image.replaceWith(replacementSvg);
  }
}

return svgElement.outerHTML;
```

This runs on the client in an effect, so I have access to the `DOMParser` API. If you're working in a server/Node environment, you'd need to replace that with some DOM parsing library like JSDOM.
