### ISSUE TITLE
Cannot read properties of undefined (reading '265') 

### ISSUE THREAD

**Issue by shinyuna** [vercel/satori#649]
Description / Observed Behavior

<img width="1473" alt="image" src="https://github.com/user-attachments/assets/d7f6bd48-b3c6-4b65-bc08-9f6326974c48">

When using the Satori library, approximately 1 out of every 2 attempts fails to generate an SVG, throwing the following error:
`Cannot read properties of undefined (reading '265')`.

Expected Behavior
Satori should generate the SVG consistently without encountering this error.

Reproduction

- https://codesandbox.io/p/devbox/pfk83h

1. npm run dev
2. Enter URL : https://pfk83h-3000.csb.app/api/og

Additional Context

Satori version: 0.12.0
Configuration details: 
- We are using the loadAdditionalAsset option to dynamically load required fonts as part of the SVG generation process.
- Local font files in both .ttf and .otf formats are being used for the dynamic font loading.

This issue might be related to the dynamic asset loading process, as the error occurs sporadically.

**Comment by shinyuna** [comment]
<img width="666" alt="image" src="https://github.com/user-attachments/assets/8d97ec4f-e1fe-4e67-a227-dd294a010a5a">

I think there is a problem with this dependency.

**Comment by erxclau** [comment]
Hey @shinyuna, the error you're running into seems similar to the error in https://github.com/vercel/satori/issues/162. Are you loading variable fonts? If not, would you be able to provide a reproduction?

**Comment by shinyuna** [comment]
> Hey @shinyuna, the error you're running into seems similar to the error in #162. Are you loading variable fonts? If not, would you be able to provide a reproduction?안녕하세요 @shinyuna, 발생한 오류는 #162의 오류와 유사한 것 같습니다. 가변 글꼴을 로드하고 있습니까? 그렇지 않다면 복제품을 제공할 수 있습니까?

I do not use variable fonts. Here is the reproduction! https://codesandbox.io/p/devbox/pfk83h  

![image](https://github.com/user-attachments/assets/c0bf4d5c-16ab-4201-a930-48ca07eb0e47)  

You can see the same error here.

**Comment by erxclau** [comment]
@shinyuna The three Noto Sans font files you are using are actually variable fonts, at least according to Google Fonts.

<img width="1469" alt="Screenshot 2024-11-28 at 2 45 03 PM" src="https://github.com/user-attachments/assets/48586bf4-3bc1-4621-9d9f-b7a71d407a05">

I think variable fonts essentially include all of the different font weights for a typeface into a single file. To fix this, you can download a specific font weight version from Google Fonts.

For example, when I download Noto_Sans_SC from Google Fonts, I get a static folder that includes all of the various font weights:

<img width="767" alt="Screenshot 2024-11-28 at 2 47 35 PM" src="https://github.com/user-attachments/assets/ba4723f7-7bfe-4a4e-a4f7-a8dfc70932dc">

I was able to generate this image after changing from variable fonts to a regular static font:

<img width="791" alt="Screenshot 2024-11-28 at 2 50 23 PM" src="https://github.com/user-attachments/assets/acd5a2b2-1d7a-4897-8351-4cea7ab37246">

Here is my fork of the reproduction: <https://codesandbox.io/p/devbox/satori-forked-9m7ypl>

**Comment by shinyuna** [comment]
> @shinyuna당신이 사용하고 있는 세 개의 Noto Sans 글꼴 파일은 적어도 Google Fonts에 따르면 실제로는 가변 글꼴입니다.
> 
> <img alt="스크린샷 2024-11-28 오후 2시 45분 03초" width="1469" src="https://private-user-images.githubusercontent.com/44459660/390894207-48586bf4-3bc1-4621-9d9f-b7a71d407a05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMzEwNzYsIm5iZiI6MTczMzEzMDc3NiwicGF0aCI6Ii80NDQ1OTY2MC8zOTA4OTQyMDctNDg1ODZiZjQtM2JjMS00NjIxLTlkOWYtYjdhNzFkNDA3YTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA5MTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZmEzNzY4NDBhYzU2ZjM1OTg1NWRjYzJjMmE1NjFhZDdmNmU3YjczNzc0ODc3MDExMzQ1M2Y1YWIyMDEyMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NpOXxX9V11kyMEdKG4myyC_HpscO06t7zC3ou3zYk4M">
> 가변 글꼴은 본질적으로 글꼴의 모든 다른 글꼴 두께를 단일 파일에 포함한다고 생각합니다. 이를 수정하려면 Google Fonts에서 특정 글꼴 두께 버전을 다운로드할 수 있습니다.
> 
> 예를 들어, Google Fonts에서 Noto_Sans_SC를 다운로드하면 다양한 글꼴 두께가 모두 포함된 정적 폴더가 생성됩니다.
> 
> <img alt="스크린샷 2024-11-28 오후 2시 47분 35초" width="767" src="https://private-user-images.githubusercontent.com/44459660/390894698-ba4723f7-7bfe-4a4e-a4f7-a8dfc70932dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMzEwNzYsIm5iZiI6MTczMzEzMDc3NiwicGF0aCI6Ii80NDQ1OTY2MC8zOTA4OTQ2OTgtYmE0NzIzZjctN2JmZS00YTRlLWE0ZjctYThkZmM3MDkzMmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA5MTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NDQ3MTQ5MDc0OGFhZDA2OTM0OGE3Y2Q0Y2E1MzA1NWVkN2Q4ZjRmMTA1YzcwYzA1YTM4MDA2ODgyNDc4MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I5WIil22VYfai0oxcYQ0M25_2sigX1GMUozQzGql_Mw">
> 가변 글꼴에서 일반 정적 글꼴로 변경한 후 이 이미지를 생성할 수 있었습니다.
> 
> <img alt="스크린샷 2024-11-28 오후 2시 50분 23초" width="791" src="https://private-user-images.githubusercontent.com/44459660/390895132-acd5a2b2-1d7a-4897-8351-4cea7ab37246.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMzEwNzYsIm5iZiI6MTczMzEzMDc3NiwicGF0aCI6Ii80NDQ1OTY2MC8zOTA4OTUxMzItYWNkNWEyYjItMWQ3YS00ODk3LTgzNTEtNGNlYTdhYjM3MjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA5MTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZTNiZjk0YTI3ZDc5ZTJiY2Y3NjBlODM0ZWQzZWVlYzM0ODE2ODI3OTA5MThiZDdlMzZjMzQ5NGY5MzlhMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Y8lVMDBvjNPkzAFRweEtnq9VHJryr3Gm8r3elzi6-Sw">
> 제가 만든 복제품은 다음과 같습니다: https://codesandbox.io/p/devbox/satori-forked-9m7ypl

I realize I was mistaken... I'm sorry for the trouble, and I really appreciate your help!

**Comment by shinyuna** [comment]
> @shinyuna The three Noto Sans font files you are using are actually variable fonts, at least according to Google Fonts.
> 
> <img alt="Screenshot 2024-11-28 at 2 45 03 PM" width="1469" src="https://private-user-images.githubusercontent.com/44459660/390894207-48586bf4-3bc1-4621-9d9f-b7a71d407a05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMzE2MTAsIm5iZiI6MTczMzEzMTMxMCwicGF0aCI6Ii80NDQ1OTY2MC8zOTA4OTQyMDctNDg1ODZiZjQtM2JjMS00NjIxLTlkOWYtYjdhNzFkNDA3YTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA5MjE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNGIxMWI2MDdmYjcyOTg0NTkxMjE0Mjg4OGE4NDcyOWNiNGNjNjdkYzU5NjZlYmQ5ZTIxMjViMGUxOGFiODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SnD5NRjj0tHfpZ_JqgBzXGdHDcsqtPeDqPh4wLZewlM">
> I think variable fonts essentially include all of the different font weights for a typeface into a single file. To fix this, you can download a specific font weight version from Google Fonts.
> 
> For example, when I download Noto_Sans_SC from Google Fonts, I get a static folder that includes all of the various font weights:
> 
> <img alt="Screenshot 2024-11-28 at 2 47 35 PM" width="767" src="https://private-user-images.githubusercontent.com/44459660/390894698-ba4723f7-7bfe-4a4e-a4f7-a8dfc70932dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMzE2MTAsIm5iZiI6MTczMzEzMTMxMCwicGF0aCI6Ii80NDQ1OTY2MC8zOTA4OTQ2OTgtYmE0NzIzZjctN2JmZS00YTRlLWE0ZjctYThkZmM3MDkzMmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA5MjE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjY2ZlOTNjOWRkM2JkZGViMTllOWYxZThlN2I1MDQxMTU1NmVkMGY4Mjg2YTMzYWFkZDc4Y2I1NDQzOWMwZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2zF-zgIlBohJ1nwXR9rTnn75ETORrwgzGob28HITnK4">
> I was able to generate this image after changing from variable fonts to a regular static font:
> 
> <img alt="Screenshot 2024-11-28 at 2 50 23 PM" width="791" src="https://private-user-images.githubusercontent.com/44459660/390895132-acd5a2b2-1d7a-4897-8351-4cea7ab37246.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMzE2MTAsIm5iZiI6MTczMzEzMTMxMCwicGF0aCI6Ii80NDQ1OTY2MC8zOTA4OTUxMzItYWNkNWEyYjItMWQ3YS00ODk3LTgzNTEtNGNlYTdhYjM3MjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA5MjE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZjA5OTMwZmMzZTU5OTllZWVjY2NhZWFlMmZhODNmNzM3M2ViYjYzOTRlZDYyOTBiMmU4MjQzZDg3MDFhMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4W66hJyCwz9_XS2w8E1sO_ICsbcfYjOcKt_ig7qg93E">
> Here is my fork of the reproduction: https://codesandbox.io/p/devbox/satori-forked-9m7ypl

I realize I was mistaken... I'm sorry for the trouble, and I really appreciate your help!
