### ISSUE TITLE
Resolving image data by default

### ISSUE THREAD

**Issue by shuding** [vercel/satori#87]
By default, Satori should fetch the resource and inline it as base64 for `<img>`. It works just like how we handle fonts (text → path) to inline all the possible dependencies. 

Furthermore, it would be great if it can:
- Resolve the image size
- Cache the image data, which can be tricky because the image might be dynamic, or taking too much memory by the cache

Also need to have an option to disable this behavior.

**Comment by transitive-bullshit** [comment]
https://github.com/sindresorhus/image-type maybe be useful here for quickly detecting MIME type of a stream / buffer.

**Comment by shuding** [comment]
Great call @transitive-bullshit , I didn't know about that package!
